### PR TITLE
SqlRole: Fix default for ServerName

### LINKED ISSUE #1592: SqlRole resource incorrect documentation or bug
#### Details of the scenario you tried and the problem that is occurring
I am trying to add new users to the role, but got:
Failed to invoke DSC Test method: Cannot validate argument on parameter 'ServerName'. The argument is null or empty. Provide an argument that is not null or empty and then try the command again.

#### Suggested solution to the issue
in documentation ServerName is not mandatory

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```json
{
    "changed": false,
    "invocation": {
        "module_args": {
            "PsDscRunAsCredential_password": null,
            "ServerRoleName": "sysadmin",
            "module_version": "latest",
            "MembersToExclude": null,
            "DependsOn": null,
            "InstanceName": "TEST",
            "resource_name": "SqlRole",
            "Ensure": "Present",
            "ServerName": null,
            "PsDscRunAsCredential_username": null,
            "Members": null,
            "MembersToInclude": [
                "DOMAIN\\Administrator",
                "DOMAIN\\SQLACL-SysAdmin"
            ]
        }
    }
}
```

#### SQL Server edition and version the target node is running
Microsoft SQL Server 2017 (RTM-CU20) (KB4541283) - 14.0.3294.2 (X64)   Mar 13 2020 14:53:45   Copyright (C) 2017 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor) 

#### SQL Server PowerShell modules present on the target node
Name  Version Path
----  ------- ----
SQLPS 14.0    C:\Program Files (x86)\Microsoft SQL Server\140\Tools\PowerShell\Modules\SQLPS\SQLPS.psd1

#### The operating system the target node is running
OsName               : Microsoft Windows Server 2019 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version and build of PowerShell the target node is running
Name                           Value
----                           -----
PSVersion                      5.1.17763.1007
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.1007
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

#### Version of the DSC module that was used
Name         Version  Path
----         -------  ----
SqlServerDsc 14.0.0   C:\Program Files\WindowsPowerShell\Modules\SqlServerDsc\14.0.0\SqlServerDsc.psd1
SqlServerDsc 13.0.0.0 C:\Program Files\WindowsPowerShell\Modules\SqlServerDsc\13.0.0.0\SqlServerDsc.psd1

### PR DESCRIPTION
**Pull request by cmcapellan**
#### Pull Request (PR) description

Fixed: 
* The `ServerName` paramer is optional and defaults to `$env:COMPUTERNAME`, but `Test-TargetResource` uses the `$PSBoundParameters` automatic variable which ignores default values for parameters. Looks like this was fixed by #1503 in several other places such as `SqlDatabasePermission` but was missed here.

#### This Pull Request (PR) fixes the following issues

- Fixes #1592

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation updated in the resource's README.md.
- [ ] Resource parameter descriptions updated in schema.mof.
- [ ] Comment-based help updated, including parameter descriptions.
- [ ] Localization strings updated.
- [ ] Examples updated.
- [ ] Unit tests updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Code changes adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1597)

### CODE REVIEW

**Comment by johlju** [comment]
@cmcapellan thank you for fixing this! I will release a patch version tomorrow.

**Comment by cmcapellan** [comment]
@johlju thanks for approving my PR! Looking forward to your release as I need this for a project I'm working on...

**Comment by johlju** [comment]
Pushed a full release now, if the test passes it will be deployed within 3 hours. There have recently been some intermittent issues when running integration tests which makes me need to re-run them manually. :/

**Comment by cmcapellan** [comment]
Great, thanks again! Now working on how to pass two variables with `SqlScriptQuery`, unfortunately the examples are all for one variable. If I figure out may submit a PR for the example...

**Comment by johlju** [comment]
It uses `Invoke-Sqlcmd` behind the scenes so examples or the documentation for that cmdlet might help you. Happily review a PR for an example for that 🙂

**Comment by cmcapellan** [comment]
Hi @johlju I see v14.2.0-preview0005 is released and there is alos 14.2 tag, are you going to release 14.2 in the next few hours?

**Comment by cmcapellan** [comment]
@johlju I see it now 😀 Thanks!

**Pull request merged**
