### PR TITLE
SqlServerDsc: Use Get-ComputerName instead of $env:COMPUTERNAME

### PR DESCRIPTION
**Pull request by johlju**
#### Pull Request (PR) description
- SqlServerDsc
  - The variable `$env:COMPUTERNAME` does not exist cross-platform which
    hinders development and testing on macOS and Linux. Instead the
    resources have been update to use the helper function `Get-ComputerName`
    which returns the current computer name cross-plattform.

No unit tests have been modified to make sure this change did not have any negative impact.
This is part of the Pester 5 conversion making sure tests can be run cross-plattform when doing development on macOS and Linux. Tests will be refactored to remove `$env:COMPUTERNAME` in the Pester 5 conversion.

#### This Pull Request (PR) fixes the following issues
None.

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation updated in the resource's README.md.
- [ ] Resource parameter descriptions updated in schema.mof.
- [x] Comment-based help updated, including parameter descriptions.
- [ ] Localization strings updated.
- [ ] Examples updated.
- [ ] Unit tests updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Code changes adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1659)

### CODE REVIEW

**Comment by johlju** [comment]
I will merge this as soon as the tests passes because I need it for the pester 5 conversion.

**Review by johlju — COMMENTED** [review]
> Reviewed 59 of 59 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1659)* status: all files reviewed, 7 unresolved discussions

___
*[source/DSCResources/DSC_SqlDatabaseObjectPermission/DSC_SqlDatabaseObjectPermission.psm1, line 740 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1659#-MPTQkON9N7TctDgOmQO:-MPTQkON9N7TctDgOmQP:bcg6vof) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c0a5b79b25135148e71615c305516b381a9198a4/source/DSCResources/DSC_SqlDatabaseObjectPermission/DSC_SqlDatabaseObjectPermission.psm1#L740)):*
> ```
>         Specifies the host name of the SQL Server to be configured. Default value
>         is the current computer name.
> ```

This can be removed since the parameter does not have a default value.
___
*[source/DSCResources/DSC_SqlProtocolTcpIp/DSC_SqlProtocolTcpIp.psm1, line 104 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1659#-MPTRUsvBbOJno7fAOfQ:-MPTRUsw5hSqYUi1or97:bjfk1bt) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c0a5b79b25135148e71615c305516b381a9198a4/source/DSCResources/DSC_SqlProtocolTcpIp/DSC_SqlProtocolTcpIp.psm1#L104)):*
> ```
> (Get-ComputerName)
> ```

Don't need parenthesis 
___
*[source/DSCResources/DSC_SqlProtocolTcpIp/DSC_SqlProtocolTcpIp.psm1, line 293 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1659#-MPTRYuICaKAZ_yBVTBN:-MPTRYuICaKAZ_yBVTBO:bjfk1bt) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c0a5b79b25135148e71615c305516b381a9198a4/source/DSCResources/DSC_SqlProtocolTcpIp/DSC_SqlProtocolTcpIp.psm1#L293)):*
> ```
> (Get-ComputerName)
> ```

Don't need parenthesis 
___
*[source/DSCResources/DSC_SqlProtocolTcpIp/DSC_SqlProtocolTcpIp.psm1, line 416 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1659#-MPTR_7RELZ93xRfRx7e:-MPTR_7RELZ93xRfRx7f:bjfk1bt) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c0a5b79b25135148e71615c305516b381a9198a4/source/DSCResources/DSC_SqlProtocolTcpIp/DSC_SqlProtocolTcpIp.psm1#L416)):*
> ```
> (Get-ComputerName)
> ```

Don't need parenthesis 
___
*[source/DSCResources/DSC_SqlReplication/DSC_SqlReplication.psm1, line 886 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1659#-MPTS7k8AIfEkHeeV-Ak:-MPTS7k8AIfEkHeeV-Al:b-rti3ld) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c0a5b79b25135148e71615c305516b381a9198a4/source/DSCResources/DSC_SqlReplication/DSC_SqlReplication.psm1#L886)):*
> ```
> return (Get-ComputerName)
> ```

Don't need parenthesis 
___
*[source/DSCResources/DSC_SqlReplication/DSC_SqlReplication.psm1, line 890 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1659#-MPTRk2HBV5wzso3OFuC:-MPTRk2HBV5wzso3OFuD:b-391l1q) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c0a5b79b25135148e71615c305516b381a9198a4/source/DSCResources/DSC_SqlReplication/DSC_SqlReplication.psm1#L890)):*
> ```
> return "$((Get-ComputerName))\$InstanceName"
> ```

Don't need parenthesis 
___
*[source/DSCResources/DSC_SqlSetup/DSC_SqlSetup.psm1, line 158 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1659#-MPTSJZj6afEZ-hbgEI-:-MPTSJZj6afEZ-hbgEI0:b-15hntz) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c0a5b79b25135148e71615c305516b381a9198a4/source/DSCResources/DSC_SqlSetup/DSC_SqlSetup.psm1#L158)):*
> ```
> $sqlHostName = (Get-ComputerName)
> ```

Don't need parenthesis

**Review by johlju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1659)* status: 55 of 59 files reviewed, all discussions resolved (waiting on @johlju)

___
*[source/DSCResources/DSC_SqlDatabaseObjectPermission/DSC_SqlDatabaseObjectPermission.psm1, line 740 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1659#-MPTQkON9N7TctDgOmQO:-MPTSmGr35aN_yeNtGWN:bb6un1j) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c0a5b79b25135148e71615c305516b381a9198a4/source/DSCResources/DSC_SqlDatabaseObjectPermission/DSC_SqlDatabaseObjectPermission.psm1#L740)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>         Specifies the host name of the SQL Server to be configured. Default value
>         is the current computer name.
> ```

This can be removed since the parameter does not have a default value.
</blockquote></details>

Done
___
*[source/DSCResources/DSC_SqlProtocolTcpIp/DSC_SqlProtocolTcpIp.psm1, line 104 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1659#-MPTRUsvBbOJno7fAOfQ:-MPTSpeFA-ZohzUg43PD:bb6un1j) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c0a5b79b25135148e71615c305516b381a9198a4/source/DSCResources/DSC_SqlProtocolTcpIp/DSC_SqlProtocolTcpIp.psm1#L104)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> (Get-ComputerName)
> ```

Don't need parenthesis 
</blockquote></details>

Done
___
*[source/DSCResources/DSC_SqlProtocolTcpIp/DSC_SqlProtocolTcpIp.psm1, line 293 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1659#-MPTRYuICaKAZ_yBVTBN:-MPTSq_5Dw3Q8wi0Vojx:bb6un1j) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c0a5b79b25135148e71615c305516b381a9198a4/source/DSCResources/DSC_SqlProtocolTcpIp/DSC_SqlProtocolTcpIp.psm1#L293)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> (Get-ComputerName)
> ```

Don't need parenthesis 
</blockquote></details>

Done
___
*[source/DSCResources/DSC_SqlProtocolTcpIp/DSC_SqlProtocolTcpIp.psm1, line 416 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1659#-MPTR_7RELZ93xRfRx7e:-MPTSrOm1yLQv1Lj9YrY:bb6un1j) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c0a5b79b25135148e71615c305516b381a9198a4/source/DSCResources/DSC_SqlProtocolTcpIp/DSC_SqlProtocolTcpIp.psm1#L416)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> (Get-ComputerName)
> ```

Don't need parenthesis 
</blockquote></details>

Done
___
*[source/DSCResources/DSC_SqlReplication/DSC_SqlReplication.psm1, line 886 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1659#-MPTS7k8AIfEkHeeV-Ak:-MPTSrz78QLP5cn_ABeS:bb6un1j) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c0a5b79b25135148e71615c305516b381a9198a4/source/DSCResources/DSC_SqlReplication/DSC_SqlReplication.psm1#L886)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> return (Get-ComputerName)
> ```

Don't need parenthesis 
</blockquote></details>

Done
___
*[source/DSCResources/DSC_SqlReplication/DSC_SqlReplication.psm1, line 890 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1659#-MPTRk2HBV5wzso3OFuC:-MPTSsYJBnE50pAdxJ_H:bb6un1j) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c0a5b79b25135148e71615c305516b381a9198a4/source/DSCResources/DSC_SqlReplication/DSC_SqlReplication.psm1#L890)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> return "$((Get-ComputerName))\$InstanceName"
> ```

Don't need parenthesis 
</blockquote></details>

Done
___
*[source/DSCResources/DSC_SqlSetup/DSC_SqlSetup.psm1, line 158 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1659#-MPTSJZj6afEZ-hbgEI-:-MPTStIkE30t9QtjtTRF:bb6un1j) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c0a5b79b25135148e71615c305516b381a9198a4/source/DSCResources/DSC_SqlSetup/DSC_SqlSetup.psm1#L158)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $sqlHostName = (Get-ComputerName)
> ```

Don't need parenthesis 
</blockquote></details>

Done

**Review by johlju — COMMENTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1659)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by johlju — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1659#-:-MPU1lxS0g98-UFW0AVq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johlju)

**Comment by Sidoran** [comment]
Hi @johlju.
I've tried to debug my DSC in the part of the WaitForAG, and I've found that the Windows server 2019 doesn't know anything about the Get-ComputerName function and throws an error when I try to call this function. I've also tried pwsh (7.2.1) on windows 10  and got the same result. I've also had not found it in SqlServerDsc.Common.psm1
Could you please tell me where I can find the source code of the Get-ComputerName function?

**Pull request merged**
