### PR TITLE
SqlServerAudit

### PR DESCRIPTION
**Pull request by Fiander**
#### Task list

- [ ] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sqlserverdsc/1433)

### CODE REVIEW

**Comment by johlju** [comment]
@Fiander Awesome work! 😃  Let me know when this is ready for review.

**Comment by Fiander** [comment]
At the moment i am combining this and a home renovation. so slow progress.
stil trying to get the code past appveyor, and then not making the codecov drop 8%.

these are only 2 out of a 3 project.
Audit ( the storage ) & ServerAuditSpecification.

with a few months DatabaseAuditSpecification should be ready.
but first i want to finish my home.

**Comment by johlju** [comment]
No worries, there a not hurry. 🙂 Sounds like a good prioritization. 😄 Tag me if I can help with the anything. Well, in the resource, not the home renovation. 😉

**Comment by Fiander** [comment]
made some last changed so it now should pass the meta checks.
the unit tests are a work in progress, but that can take two weeks.

**Comment by Fiander** [comment]
Hi, I finally gotten far enough with the house so I can continu with this.
I completed the integration test for the ServerAudit, and started with the integration tests for the ServerAuditSpecification. they wil be ready soon.

but I am absolutely not experienced enough for the unit testing. I truly have no clue on where to start and what to do. Are they really needed? I read trough some of the others, and they seem to do the same as the integration tests but not to an actual server but to some fake smo objects who are pretending to be an actual SQL Server? is this correct?

**Comment by johlju** [comment]
Sorry that I have not answered for a long time, been busy getting the new CI pipeline working for the DSC Community.

Unit tests is needed. Without them we don't merge changes. Unit tests can verify that all code paths work, which can be harder to do with integration tests some tests might not even be able, or harder, to be tested, like throwing an error or changing the state of the build worker in such a manner that it cannot recover. Unit tests also shows us the code coverage of the tests where integration tests does not since the LCM is running the tests. Unit tests mocks the actually action and instead returns a state, the unit test verifies that the state returned is the one that was expected. Normally you mock cmdlets, but since the are so few cmdlets for SQL Server we have to resort to using the SMO in the code. That means that sometimes we have to mock the SMO classes, or make wrapper functions for the SMO calls that in turn we can mock easily. Those wrappers have minimal code (one-liners) and does not need to be unit tested.

The new CI pipeline has merged in this repository. This changed the folder structure, and also removed the dev branch. Please rebase against the master branch, and make sure to get your changes into the the file in the new location (under `source` folder). 😃 

Read more here about the new coding workflow: 
https://dsccommunity.org/guidelines/contributing/#understand-the-coding-workflow
https://dsccommunity.org/guidelines/testing-guidelines/#running-tests
You can also use Invoke-Pester once you run `build.ps1 -Task build` (not documented yet)
https://dsccommunity.org/guidelines/contributing/#attach-your-fork-to-a-free-azure-devops-organization

Let me know if you need further help.

**Pull request closed without merging**
