### PR TITLE
BREAKING CHANGE: SqlWaitForAG: Evaluate so that Availability Group is available

### LINKED ISSUE #1569: SqlWaitForAG: Does not evaluate if the Availability Group was successfully created
SqlWaitForAG resource evaluates if the Windows Failover Cluster role/group has been created. But the Windows Failover Cluster role/group is created before the Availability Group is in a ready state. When the Windows Failover Cluster role/group is found the resource will wait one more time according to the value of `RetryIntervalSec` before returning. There is currently no check to validate that the Availability Group was successfully created and is in a ready state.

### PR DESCRIPTION
**Pull request by Fiander**
#### Pull Request (PR) description

The resource now waits for the clustergroup to be made, and when clusterGroup is found,
it checks for the existance of the AvailibilityGroup.

#### This Pull Request (PR) fixes the following issues

Fixes  #1569
#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [x] Resource documentation updated in the resource's README.md.
- [x] Resource parameter descriptions updated in schema.mof.
- [x] Comment-based help updated, including parameter descriptions.
- [ ] Localization strings updated.
- [x] Examples updated.
- [x] Unit tests updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Code changes adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1636)

### CODE REVIEW

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1636)* status: all files reviewed, 13 unresolved discussions (waiting on @Fiander)

___
*[CHANGELOG.md, line 10 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1636#-MMpR83kAMzX4tq5QUry:-MMpR83kAMzX4tq5QUrz:b-1eb5nu) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/4390b4e70d3fe5b164c6b859a2b1542f97110831/CHANGELOG.md#L10)):*
> ```
> AG
> ```

Can we write out AG to 'Availability Group' to avoid abbreviations that could be misleading.
___
*[CHANGELOG.md, line 10 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1636#-MMpRYUnA4W6iSaGzEo0:-MMpRYUnA4W6iSaGzEo1:b-rjy7ww) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/4390b4e70d3fe5b164c6b859a2b1542f97110831/CHANGELOG.md#L10)):*
> ```
> DSC now waits...
> ```

Maybe: "The resource now waits...", or "The DSC resource now waits..."
___
*[CHANGELOG.md, line 11 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1636#-MMpRsJk9I9QTMQXi06H:-MMpRsJk9I9QTMQXi06I:b-waba3s) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/4390b4e70d3fe5b164c6b859a2b1542f97110831/CHANGELOG.md#L11)):*
> ```
> This is a breaking change
> ```

Remove this and add `BREAKING CHANGE:` before the entry so it easy to find the breaking change entries. We can also mention what parameters was added and why.
___
*[CHANGELOG.md, line 12 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1636#-MMpPy-X6nZP3IHKKxb9:-MMpPy-X6nZP3IHKKxbA:bn9scaz) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/4390b4e70d3fe5b164c6b859a2b1542f97110831/CHANGELOG.md#L12)):*
> ```Markdown
>     DSC now waits for the AG to become Available.
>     This is a breaking change. Two parameters where added to test get and set resource.
> ```

We can remove this blank line.
___
*[source/DSCResources/DSC_SqlWaitForAG/DSC_SqlWaitForAG.psm1, line 27 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1636#-MMpSA3p9W8cki7LEqgx:-MMpSA3p9W8cki7LEqgy:beg8c78) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/4390b4e70d3fe5b164c6b859a2b1542f97110831/source/DSCResources/DSC_SqlWaitForAG/DSC_SqlWaitForAG.psm1#L27)):*
> ```
> AG group
> ```

Can we write out AG to 'Availability Group' to avoid abbreviations that could be misleading. Throughout out the text. Also in all other comment-based help below.
___
*[source/DSCResources/DSC_SqlWaitForAG/DSC_SqlWaitForAG.psm1, line 28 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1636#-MMpQVRf6YZEwNhgNSpm:-MMpQVRf6YZEwNhgNSpn:b636nxa) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/4390b4e70d3fe5b164c6b859a2b1542f97110831/source/DSCResources/DSC_SqlWaitForAG/DSC_SqlWaitForAG.psm1#L28)):*
> ```
>         When also the AG group has been
>         found, dsc wil wait for RetryIntervalSec amount of time once more before returning.
> ```

Maybe: "When the availability group have been found the resource will also wait this amount of time before returning."

Also in all other comment-based help below.
___
*[source/DSCResources/DSC_SqlWaitForAG/DSC_SqlWaitForAG.psm1, line 69 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1636#-MMpSSw614ZwjLzRgqlz:-MMpSSw614ZwjLzRgqm-:b9f73lg) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/4390b4e70d3fe5b164c6b859a2b1542f97110831/source/DSCResources/DSC_SqlWaitForAG/DSC_SqlWaitForAG.psm1#L69)):*
> ```
> #No ClusterName
> ```

Space after the # 
___
*[source/DSCResources/DSC_SqlWaitForAG/DSC_SqlWaitForAG.psm1, line 82 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1636#-MMpS_Ox2eIDc1OZ0hPX:-MMpS_Ox2eIDc1OZ0hPY:b-vxocz6) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/4390b4e70d3fe5b164c6b859a2b1542f97110831/source/DSCResources/DSC_SqlWaitForAG/DSC_SqlWaitForAG.psm1#L82)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>         Write-Verbose -Message (
>             $ServerName
>         )
>         Write-Verbose -Message (
>             $InstanceName
>         )
> ```
</details>


We can remove this, it looks like debug code. They could be added to the localized string `FoundClusterGroup` instead.
___
*[source/DSCResources/DSC_SqlWaitForAG/DSC_SqlWaitForAG.psm1, line 87 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1636#-MMpSsUJ3UxUJorM9NH5:-MMpSsUJ3UxUJorM9NH6:bj6n6vc) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/4390b4e70d3fe5b164c6b859a2b1542f97110831/source/DSCResources/DSC_SqlWaitForAG/DSC_SqlWaitForAG.psm1#L87)):*
> ```
> $serverObject -ne $null
> ```

such evaluations should always start with $null on the left side `$null -ne $serverObject`, but in this cause we can simply use `if ($serverObject)`.
___
*[source/DSCResources/DSC_SqlWaitForAG/DSC_SqlWaitForAG.psm1, line 89 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1636#-MMpTEowCmxNrQaMuNmR:-MMpTEowCmxNrQaMuNmS:byjxuy7) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/4390b4e70d3fe5b164c6b859a2b1542f97110831/source/DSCResources/DSC_SqlWaitForAG/DSC_SqlWaitForAG.psm1#L89)):*
> ```
>             Write-Verbose -Message (
>                 $serverObject
>             )
> ```

Should be removed, looks like debug code.
___
*[source/DSCResources/DSC_SqlWaitForAG/DSC_SqlWaitForAG.psm1, line 93 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1636#-MMpUr5bBhqEIWY_5T5w:-MMpUr5bBhqEIWY_5T5x:bfwb8up) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/4390b4e70d3fe5b164c6b859a2b1542f97110831/source/DSCResources/DSC_SqlWaitForAG/DSC_SqlWaitForAG.psm1#L93)):*
> ```
> if ($serverObject.IsHadrEnabled )
> ```

If this fails we should output that Hadr is missing.
___
*[source/DSCResources/DSC_SqlWaitForAG/DSC_SqlWaitForAG.psm1, line 97 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1636#-MMpUwCm3Ydripif4CZt:-MMpUwCm3Ydripif4CZu:bptuhlw) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/4390b4e70d3fe5b164c6b859a2b1542f97110831/source/DSCResources/DSC_SqlWaitForAG/DSC_SqlWaitForAG.psm1#L97)):*
> ```
> if ( $availabilityGroup )
> ```

In this fails we should output that availability group is missing.
___
*[source/DSCResources/DSC_SqlWaitForAG/README.md, line 5 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1636#-MMpW3NgEhE1u7uCaGKu:-MMpW3Nh1mCDYXFbe6Mu:bwq0fuo) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/4390b4e70d3fe5b164c6b859a2b1542f97110831/source/DSCResources/DSC_SqlWaitForAG/README.md#L5)):*
> ```
> When te cluster group is found, it wil search and wait for the Availability Group to
> become available. When the AG is found, it wil wait for one last TimeOut period.
> ```

Maybe: "When the cluster group is found it will wait for the availability group to become available. When the availability group have been found the resource will wait the amount of time specified in the parameter `RetryIntervalSec` before returning."

**Review by Fiander — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1636)* status: 3 of 8 files reviewed, 13 unresolved discussions (waiting on @Fiander and @johlju)

___
*[CHANGELOG.md, line 10 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1636#-MMpR83kAMzX4tq5QUry:-MMrB5Sq43HmN-l-Dusn:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/4390b4e70d3fe5b164c6b859a2b1542f97110831/CHANGELOG.md#L10)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> AG
> ```

Can we write out AG to 'Availability Group' to avoid abbreviations that could be misleading.
</blockquote></details>

Done.
___
*[CHANGELOG.md, line 10 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1636#-MMpRYUnA4W6iSaGzEo0:-MMrB6akAliRSqC4F9An:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/4390b4e70d3fe5b164c6b859a2b1542f97110831/CHANGELOG.md#L10)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> DSC now waits...
> ```

Maybe: "The resource now waits...", or "The DSC resource now waits..."
</blockquote></details>

Done.
___
*[CHANGELOG.md, line 11 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1636#-MMpRsJk9I9QTMQXi06H:-MMrB9Kz2BCfqjm-fwRK:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/4390b4e70d3fe5b164c6b859a2b1542f97110831/CHANGELOG.md#L11)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> This is a breaking change
> ```

Remove this and add `BREAKING CHANGE:` before the entry so it easy to find the breaking change entries. We can also mention what parameters was added and why.
</blockquote></details>

Done.
___
*[CHANGELOG.md, line 12 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1636#-MMpPy-X6nZP3IHKKxb9:-MMrB9g_98Fog6LZhlAJ:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/4390b4e70d3fe5b164c6b859a2b1542f97110831/CHANGELOG.md#L12)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We can remove this blank line.
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_SqlWaitForAG/DSC_SqlWaitForAG.psm1, line 27 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1636#-MMpSA3p9W8cki7LEqgx:-MMrBFnO917vlrOAB2Tj:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/4390b4e70d3fe5b164c6b859a2b1542f97110831/source/DSCResources/DSC_SqlWaitForAG/DSC_SqlWaitForAG.psm1#L27)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> AG group
> ```

Can we write out AG to 'Availability Group' to avoid abbreviations that could be misleading. Throughout out the text. Also in all other comment-based help below.
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_SqlWaitForAG/DSC_SqlWaitForAG.psm1, line 28 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1636#-MMpQVRf6YZEwNhgNSpm:-MMrBG654TiJEaJWV3Mc:bpz52u7) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/4390b4e70d3fe5b164c6b859a2b1542f97110831/source/DSCResources/DSC_SqlWaitForAG/DSC_SqlWaitForAG.psm1#L28)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>         When also the AG group has been
>         found, dsc wil wait for RetryIntervalSec amount of time once more before returning.
> ```

Maybe: "When the availability group have been found the resource will also wait this amount of time before returning."

Also in all other comment-based help below.
</blockquote></details>

Done, but changed  "have" to "has" >> one group has been found, more groups have been found.
___
*[source/DSCResources/DSC_SqlWaitForAG/DSC_SqlWaitForAG.psm1, line 69 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1636#-MMpSSw614ZwjLzRgqlz:-MMrBXyL9FLdD4hnjEGu:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/4390b4e70d3fe5b164c6b859a2b1542f97110831/source/DSCResources/DSC_SqlWaitForAG/DSC_SqlWaitForAG.psm1#L69)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> #No ClusterName
> ```

Space after the # 
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_SqlWaitForAG/DSC_SqlWaitForAG.psm1, line 82 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1636#-MMpS_Ox2eIDc1OZ0hPX:-MMrBdGp5B2ho3rJc_D8:b-xei62o) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/4390b4e70d3fe5b164c6b859a2b1542f97110831/source/DSCResources/DSC_SqlWaitForAG/DSC_SqlWaitForAG.psm1#L82)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>         Write-Verbose -Message (
>             $ServerName
>         )
>         Write-Verbose -Message (
>             $InstanceName
>         )
> ```

We can remove this, it looks like debug code. They could be added to the localized string `FoundClusterGroup` instead.
</blockquote></details>

Done. was a left over, removed them.
___
*[source/DSCResources/DSC_SqlWaitForAG/DSC_SqlWaitForAG.psm1, line 87 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1636#-MMpSsUJ3UxUJorM9NH5:-MMrBnmp14r72rS1y9pH:b-exzqku) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/4390b4e70d3fe5b164c6b859a2b1542f97110831/source/DSCResources/DSC_SqlWaitForAG/DSC_SqlWaitForAG.psm1#L87)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $serverObject -ne $null
> ```

such evaluations should always start with $null on the left side `$null -ne $serverObject`, but in this cause we can simply use `if ($serverObject)`.
</blockquote></details>

Done,  i have changed it to if ($serverObject). 
___
*[source/DSCResources/DSC_SqlWaitForAG/DSC_SqlWaitForAG.psm1, line 89 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1636#-MMpTEowCmxNrQaMuNmR:-MMrDr1dCRo0DPajWg93:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/4390b4e70d3fe5b164c6b859a2b1542f97110831/source/DSCResources/DSC_SqlWaitForAG/DSC_SqlWaitForAG.psm1#L89)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>             Write-Verbose -Message (
>                 $serverObject
>             )
> ```

Should be removed, looks like debug code.
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_SqlWaitForAG/README.md, line 5 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1636#-MMpW3NgEhE1u7uCaGKu:-MMrhzd49KT7htLJAvua:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/4390b4e70d3fe5b164c6b859a2b1542f97110831/source/DSCResources/DSC_SqlWaitForAG/README.md#L5)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> When te cluster group is found, it wil search and wait for the Availability Group to
> become available. When the AG is found, it wil wait for one last TimeOut period.
> ```

Maybe: "When the cluster group is found it will wait for the availability group to become available. When the availability group have been found the resource will wait the amount of time specified in the parameter `RetryIntervalSec` before returning."
</blockquote></details>

Done.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 3 of 5 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1636#-:-MMzACNv7DESMD5lU2EO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[source/DSCResources/DSC_SqlWaitForAG/DSC_SqlWaitForAG.psm1, line 28 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1636#-MMpQVRf6YZEwNhgNSpm:-MMz97qj7kBVZpr5_TI3:bjhj0dx) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/4390b4e70d3fe5b164c6b859a2b1542f97110831/source/DSCResources/DSC_SqlWaitForAG/DSC_SqlWaitForAG.psm1#L28)):*
<details><summary><i>Previously, Fiander wrote…</i></summary><blockquote>

Done, but changed  "have" to "has" >> one group has been found, more groups have been found.
</blockquote></details>

Thanks for correcting my spelling, I always have a problem with those nuances. :slightly_smiling_face:

**Comment by johlju** [comment]
@Fiander this was a great addition! Thank you! 😃

**Pull request merged**
