### PR TITLE
SqlProtocol: Changes datatype for schema property KeepAlive

### LINKED ISSUE #1645: SqlProtocol: KeepAlive parameter/property using incorrect data type
#### Details of the scenario you tried and the problem that is occurring

It appears that if you use the `SqlProtocol`, DSC resource and specify a `KeepAlive` parameter value that is different to the value already set/present, the resource will throw the following error:

`Exception setting "Value": "Type mismatch when trying to assign value to property KeepAlive. Received System.UInt16 instead of System.Int32.".`

The `SqlProtocol` resource currently uses a `UInt16` datatype but when the resource tries to update/set the relevant value by calling...

```PowerShell
$serverProtocolProperties.ProtocolProperties['KeepAlive'].Value = $KeepAlive
```

... currently line 304, in the `Set-TargetResource` method in [`DSC_SqlProtocol.psm1`](https://github.com/dsccommunity/SqlServerDsc/blob/master/source/DSCResources/DSC_SqlProtocol/DSC_SqlProtocol.psm1), it seems to be expecting an `Int32` data type instead.

Note that if the `KeepAlive` value is set to the **same** value as it was previously, no error/exception will be thrown because the update statement call is skipped.

#### Verbose logs showing the problem
N/A

#### Suggested solution to the issue
I believe the DSC resource `KeepAlive` parameter/property of the `SqlProtocol`, DSC resource needs to be updated from a `UInt16` to an `Int32` data type.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
N/A - No config, but example PowerShell around the specific line of code is below.

NOTE: The assignment of `$serverProtocolProperties` was performed using example script from #1628

```PowerShell

$serverProtocolProperties # Assigned by other script in issue #1628

<...snip...>

# 'UInt16' Example
$currentKeepAlive = $serverProtocolProperties.ProtocolProperties['KeepAlive'].Value
Write-Output "Current: $currentKeepAlive"

[UInt16]$KeepAlive = $currentKeepAlive + 1  # Current data type (UInt16)
$serverProtocolProperties.ProtocolProperties['KeepAlive'].Value = $KeepAlive  # !!! EXCEPTION THROWN !!!

$currentKeepAlive = $serverProtocolProperties.ProtocolProperties['KeepAlive'].Value
Write-Output "PostUpdate: $currentKeepAlive"




# 'Int32' Example
$currentKeepAlive = $serverProtocolProperties.ProtocolProperties['KeepAlive'].Value
Write-Output "Current: $currentKeepAlive"

[Int32]$KeepAlive = $currentKeepAlive + 1 # Required data type (Int32)
$serverProtocolProperties.ProtocolProperties['KeepAlive'].Value = $KeepAlive  # Updates without exception

$currentKeepAlive = $serverProtocolProperties.ProtocolProperties['KeepAlive'].Value
Write-Output "PostUpdate: $currentKeepAlive"


```

#### SQL Server edition and version the target node is running
Microsoft SQL Server 2017 (RTM) - 14.0.1000.169 (X64)   Aug 22 2017 17:04:49   Copyright (C) 2017 Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: ) (Hypervisor) 

#### SQL Server PowerShell modules present on the target node
SqlServer - 21.1.18229
SQLPS - 14.0

#### The operating system the target node is running
OsName               : Microsoft Windows Server 2012 R2 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 9600.19846.amd64fre.winblue_ltsb_escrow.200923-1735
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version and build of PowerShell the target node is running                                                                                                                      
PSVersion                      5.1.14409.1018                                                                                                                            
PSEdition                      Desktop                                                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                   
BuildVersion                   10.0.14409.1018                                                                                                                           
CLRVersion                     4.0.30319.42000                                                                                                                           
WSManStackVersion              3.0                                                                                                                                       
PSRemotingProtocolVersion      2.3                                                                                                                                       
SerializationVersion           1.1.0.1  

#### Version of the DSC module that was used
14.2.1

### PR DESCRIPTION
**Pull request by Fiander**
#### Pull Request (PR) description

Changed KeepAlive Type from UInt16 to Int32 to reflect the actual WMI.ManagementObject

#### This Pull Request (PR) fixes the following issues

- Fixes #1645
#### Task list

- [X] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation updated in the resource's README.md.
- [X] Resource parameter descriptions updated in schema.mof.
- [ ] Comment-based help updated, including parameter descriptions.
- [ ] Localization strings updated.
- [ ] Examples updated.
- [ ] Unit tests updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [X] Code changes adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1646)

### CODE REVIEW

**Review by johlju — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1646)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by johlju** [comment]
@Fiander when you have time can you resolve the conflicting file? 🙂

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1646)* status: all files reviewed, 1 unresolved discussion (waiting on @Fiander)

___
*[source/DSCResources/DSC_SqlProtocol/DSC_SqlProtocol.schema.mof, line 9 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1646#-MOHtyKLBR4GcAxSmbae:-MOHtyKLBR4GcAxSmbaf:bseibh8) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/b5e8ca701c3fc25026443ae3cb18c4e74eb813c8/source/DSCResources/DSC_SqlProtocol/DSC_SqlProtocol.schema.mof#L9)):*
> ```
> Int32
> ```

Should be `SInt32`, see https://docs.microsoft.com/en-us/windows/win32/wmisdk/numbers

**Comment by johlju** [comment]
@Fiander It seems that MOF uses SInt instead of Int to express signed integer. 🙂

**Comment by Fiander** [comment]
Sint in a MOF.... oke, never used that one before. but it is done

**Comment by johlju** [comment]
I don't remember if I used that one either, signed int that is. 🤔  Usually property values don't need to be negative. 🙂  
Anyway, build passed so it looks better so far. 😄

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1646#-:-MOIA7c-EDJREM5Ir70f:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
