### PR TITLE
SqlAG: unit tests converted to Pester 5

### LINKED ISSUE #1735: SqlAg: DtcSupportEnabled should be updatable
Documentation for SqlAG resource says DtcSupportEnabled "can not be altered once the availability group is created and is ignored if it is the case.". But [Configure distributed transactions for an Always On availability group](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/configure-availability-group-for-distributed-transactions?view=sql-server-2016#alter-an-availability-group-for-distributed-transactions) mentions this is actually possible starting with SQL Server 2016 SP2. Any plans to implement this?

### LINKED ISSUE #1752: SqlAG: Refactor unit tests to support Pester 5
Due to the size of the PR #1550 it was a pain to rebase it for each contribution to the repository, for that reason it was merge prior to having refactored the unit test for SqlAG. The unit tests for SqlAG are currently skipped until refactor has been made.

### PR DESCRIPTION
**Pull request by Sidoran**
#### Pull Request (PR) description

Convert SqlAG unit tests to Pester 5 plus add missed parameters to a SQLAG Test and Get functions.
Fix unit test for the SQLAGReplica

#### This Pull Request (PR) fixes the following issues

- Fixes #1752
- Fixes #1735

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation updated in the resource's README.md.
- [ ] Resource parameter descriptions updated in schema.mof.
- [ ] Comment-based help updated, including parameter descriptions.
- [ ] Localization strings updated.
- [ ] Examples updated.
- [x] Unit tests updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Code changes adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1987)

### CODE REVIEW

**Review by johlju — CHANGES_REQUESTED** [review]
Looking good, than you for this! Just a tiny comment.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1987#-:-NldVxQ81WBxs6D2cuK5:blen4m5)* status: all files reviewed, 1 unresolved discussion (waiting on @Sidoran)

___
*[`source/DSCResources/DSC_SqlAG/DSC_SqlAG.psm1` line 755 at r1](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1987#-NldVIxH8_R3eS1_ObvR:-NldVIxH8_R3eS1_ObvS:b-elzq7t) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/02bcd594a0ba005badc7bb88123052a1df423ab0/source/DSCResources/DSC_SqlAG/DSC_SqlAG.psm1#L755)):*
> ```PowerShell
>             <#
>                 Add properties compatible with SQL Server 2016 or later versions
>                 DtcSupportEnabled is enabled at the creation of the Availability Group only, hence it will not be checked in this block
> ```

We should remove this comment from the code as well.



_Code quote:_
```PowerShell
DtcSupportEnabled is enabled at the creation of the Availability Group only, hence it will not be checked in this block
```

**Comment by Sidoran** [comment]
@johlju, Looks like starting from the SQL 2016 SP2, we can change the DtcSupportEnabled option for the existing Availability group [proof](https://learn.microsoft.com/en-us/sql/database-engine/availability-groups/windows/configure-availability-group-for-distributed-transactions?view=sql-server-ver16#alter-an-availability-group-for-distributed-transactions)
I removed the comment as you suggested.
I also have a question. During this task, I tried to find a way to work with the code coverage in VSCode and see which lines are covered by tests and which are not. Unfortunately, I have not found a working solution. Can you please suggest a way or guide me to a manual on how to display code coverage in VSCode for the SQLServerDSC?

**Comment by johlju** [comment]
I haven't tested using code coverage in VS Code. I always run the code coverage in command line using `Invoke-Pester`. But there is this if you want to try using it in VS Code: https://gist.github.com/nohwnd/efc339339dc328d93e0fe000249aea25

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1987#-:-NlinURG6KzWHmBDiYYc:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Sidoran)

**Pull request merged**
