### PR TITLE
SqlPermission: Permission parameter should be mandatory

### LINKED ISSUE #1761: SQLPermission: Get-TargetResource expects a mandatory parameter
### Problem description

When doing a get on SQLPermission resource it expects the parameter 'permission' to be passed into it. If the permission parameter isn't passed through then we hit an Exception.

### Verbose logs

```text
PowerShell DSC resource DSC_SqlPermission  failed to execute Get-TargetResource functionality with error message: System.InvalidOperationException: Unexpected result when trying to get permissions for 'domain\testuser1'. ---> 
System.Management.Automation.ParameterBindingValidationException: Cannot validate argument on parameter
'Permission'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again. --->
System.Management.Automation.ValidationMetadataException: The argument is null or empty. Provide an argument that is not
 null or empty, and then try the command again.
   at System.Management.Automation.ValidateNotNullOrEmptyAttribute.Validate(Object arguments, EngineIntrinsics engineInt
rinsics)
   at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommand
Parameter parameterMetadata,
ParameterBindingFlags flags)
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exc
eption)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   --- End of inner exception stack trace ---
```

### DSC configuration

```powershell
$InvokeParams = @{

Name = 'SqlPermission';
Method = 'get';
Property = @{instancename = 'MSSQLSERVER'; principal = 'domain\testuser1'};
ModuleName = @{ModuleName = 'C:/ProgramData/PuppetLabs/puppet/cache/lib/puppet_x/sqlserverdsc/dsc_resources/SqlServerDsc/SqlServerDsc.psd1';
RequiredVersion = '15.2.0'}}
Invoke-DscResource @InvokeParams
```

### Suggested solution

make permission to be a mandatory parameter in the sqlpermission resource. Doing this returns without any problems.

```
$InvokeParams = @{
Name = 'SqlPermission';
Method = 'get';
Property = @{instancename = 'MSSQLSERVER'; principal = 'domain\testuser1'; permission = 'AlterAnyAvailabilityGroup', 'ViewServerState'};
ModuleName = @{ModuleName = 'C:/ProgramData/PuppetLabs/puppet/cache/lib/puppet_x/sqlserverdsc/dsc_resources/SqlServerDsc/SqlServerDsc.psd1';
RequiredVersion = '15.2.0'}}
Invoke-DscResource @InvokeParams
```
```
ConfigurationName    :
DependsOn            :
ModuleName           : C:/ProgramData/PuppetLabs/puppet/cache/lib/puppet_x/sqlserverdsc/dsc_resources/SqlServerDsc/SqlServerDsc.psd1
ModuleVersion        : 15.2.0
PsDscRunAsCredential :
ResourceId           :
SourceInfo           :
Ensure               : Absent
InstanceName         : MSSQLSERVER
Permission           : {}
Principal            : domain\testuser1
ServerName           : SQL01
PSComputerName       : localhost
```

### SQL Server edition and version

```
Microsoft SQL Server 2019 (RTM-CU16-GDR) (KB5014353) - 15.0.4236.7 (X64)   May 29 2022 15:55:47   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: )
```

### SQL Server PowerShell modules

``` 
Name  Version Path
----  ------- ----
SQLPS 15.0    E:\Program Files (x86)\Microsoft SQL Server\150\Tools\PowerShell\Modules\SQLPS\SQLPS.psd1
```

### Operating system

```text
OsName               : Microsoft Windows Server 2019 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
```

### PowerShell version

```
Name                           Value
----                           -----
PSVersion                      5.1.17763.1490
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.1490
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### SqlServerDsc version

```
15.2.0
```

### PR DESCRIPTION
**Pull request by wahid99**
#### Pull Request (PR) description
Permission parameter within SqlPermission should be mandatory, otherwise get-targetresource throws an exception.

#### This Pull Request (PR) fixes the following issues

- Fixes #1761

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation updated in the resource's README.md.
- [x] Resource parameter descriptions updated in schema.mof.
- [ ] Comment-based help updated, including parameter descriptions.
- [ ] Localization strings updated.
- [ ] Examples updated.
- [ ] Unit tests updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Code changes adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1762)

### CODE REVIEW

**Comment by johlju** [comment]
That PR changes SqlAG and not SqlPermission (as discussed in issue #1761) - could you please take a look at the PR again?

**Comment by wahid99** [comment]
Reverted previous change. Updated correct resource. Committed and squashed to clean up.

**Comment by wahid99** [comment]
@johlju - Please kindly take a look at this one again when you have some time please? Thanks

**Comment by johlju** [comment]
I'm waiting for the build workers to get the Windows patch for DSC so the integration tests can run. I will review then.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1762#-:-N83dOxh0ZonADBkG-Mr:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wahid99)

**Pull request merged**
