### PR TITLE
BREAKING CHANGE: SqlRole: Resource overhaul for tests

### LINKED ISSUE #550: SqlRole: User 'sa' is not allowed to be dropped from role sysadmin
**Details of the scenario you tried and the problem that is occurring:**
I have the following 2 DSC Resource statements one works and the other does not. The first successfully adds the account to the securityadmin SQL role and the second fails to add the same account to the sysadmin SQL role.

`
**The DSC configuration that is using the resource (as detailed as possible):**

```
xSQLServerRole Set_securityadmin_Roles4_FarmSetup{

    Members = @($FarmSetupCredential.UserName)
    SQLServer = $SqlServerName
    SQLInstanceName = $SqlInstanceName
    ServerRoleName = "securityadmin"
    Ensure = "Present"
}
xSQLServerRole Set_sysadmin_Roles4_FarmSetup{

    Members = @($FarmSetupCredential.UserName)
    SQLServer = $SqlServerName
    SQLInstanceName = $SqlInstanceName
    ServerRoleName = "sysadmin"
    Ensure = "Present"
}
```
Error Message for Set_sysadmin_Roles4_FarmSetup

```
PowerShell DSC resource MSFT_xSQLServerRole  failed to execute Set-TargetResource functionality with error message: Failed to drop member sa to the 
server role named sysadmin on SP-SQL1\MSSQLSERVER. InnerException: Exception calling "DropMember" with "1" argument(s): "Drop member failed for 
ServerRole 'sysadmin'. " 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : SP-SQL1
```

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
I am using SQL 2016 on Windows Server 2012 R2

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**

xSQLServerRole  v 7.0.0.0

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
SQLServer  7.0.0.0

### PR DESCRIPTION
**Pull request by Fiander**
Major overhaul of SQLRole, added tests, and fix for issue #550

#### Pull Request (PR) description
some remodeling of SqlRole.
lots of extra tests,
fix for #550 

#### This Pull Request (PR) fixes the following issues
Fixes #550 

#### Task list

- [X] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation updated in the resource's README.md.
- [ ] Resource parameter descriptions updated in schema.mof.
- [ ] Comment-based help updated, including parameter descriptions.
- [x] Localization strings updated.
- [ ] Examples updated.
- [X] Unit tests updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Code changes adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1631)

### CODE REVIEW

**Comment by Fiander** [comment]
This is  the same as #1623. when i did #1623, i did everything in the local master branch.
This is a rebase of #1623 now in its own branch. everything else is the same.

i left #1623 open for the comments.

**Review by johlju — CHANGES_REQUESTED** [review]
Awesome work on this! Sorry that I am slow to review this one, that is not normal! I'm usually have the reviews and PR merged within a week. The day job is just overwhelming at the moment (large project) and my head is exhausted when I get home. :slightly_smiling_face:

Just two small comments and then we merge this one! :slightly_smiling_face:   

> Reviewed 5 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1631#-:-MMeIdD543WC1nol-18K:b-5667b5)* status: all files reviewed, 2 unresolved discussions (waiting on @Fiander)

___
*[CHANGELOG.md, line 10 at r2](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1631#-MMeGHU9-HsOtdj2NNJj:-MMeGHU9-HsOtdj2NNJk:bygs8u5) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/deffc845effc7aa6b1217bf0aad6e63caa14ae9c/CHANGELOG.md#L10)):*
> ```
> Removed decision...
> ```

Please add 'BREAKING CHANGE:' to this entry. `BREAKING CHANGE: Removed decision...`
___
*[source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1, line 672 at r2](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1631#-MMeHCITBUfGBkeG1NSY:-MMeHCITBUfGBkeG1NSZ:b-3khf6y) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/deffc845effc7aa6b1217bf0aad6e63caa14ae9c/source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1#L672)):*
> ```PowerShell
>     )
> 
>     if ($Members)
> ```

Can we do the evaluation like this to save a few rows?

```
if ($ServerRoleName -eq 'sysadmin')
{
    if ($Members)
    {
        if ($Members -notcontains 'SA')
        {
            $Members += 'SA'
        }
    }
    else
    {
        if ($MembersToExclude -contains 'SA')
        {
            $MembersToExclude = $MembersToExclude -ne 'SA'
        }
    }
}
```

**Comment by johlju** [comment]
@Fiander I keep an eye for commits on this and I will quickly resolve the comments and merge. 🙂  Thank you for sticking out!

**Review by Fiander — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1631)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @Fiander and @johlju)

___
*[source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1, line 672 at r2](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1631#-MMeHCITBUfGBkeG1NSY:-MMePln41NOUro9YFVZQ:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/deffc845effc7aa6b1217bf0aad6e63caa14ae9c/source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1#L672)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Can we do the evaluation like this to save a few rows?

```
if ($ServerRoleName -eq 'sysadmin')
{
    if ($Members)
    {
        if ($Members -notcontains 'SA')
        {
            $Members += 'SA'
        }
    }
    else
    {
        if ($MembersToExclude -contains 'SA')
        {
            $MembersToExclude = $MembersToExclude -ne 'SA'
        }
    }
}
```
</blockquote></details>

Done.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1631#-:-MMeQ3k60PwJqToVVht3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by johlju** [comment]
Will merge as soon as the tests passes.

**Comment by Fiander** [comment]
No problem. Now that is sorted out my own Branches, i am not hindert by my own work anymore. take the time you need.
I have two more resources in the pipeline for you. (#1632 and #1633 )

**Comment by Fiander** [comment]
damm it. crashed again on SQLLogin.

2020-11-21T11:11:23.7970129Z VERBOSE: [WIN-U9C4GIKUSPU]: LCM:  [ Start  Get      ]      
2020-11-21T11:11:24.1770576Z       [-] Should be able to call Get-DscConfiguration without throwing 429ms
2020-11-21T11:11:24.2982432Z         Expected no exception to be thrown, but an exception "Connecting to remote server localhost failed with the following error message : Illegal operation attempted on a registry key that has been marked for deletion. For more information, see the about_Remote_Troubleshooting Help topic." was thrown from D:\a\1\s\tests\Integration\DSC_SqlLogin.Integration.Tests.ps1:99 char:52
2020-11-21T11:11:24.2997509Z             + ... urrentConfiguration = Get-DscConfiguration -Verbose -ErrorAction Stop
2020-11-21T11:11:24.3013810Z             +                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
2020-11-21T11:11:24.3030094Z         100:                 } | Should -Not -Throw
2020-11-21T11:11:24.3047710Z         at <ScriptBlock>, D:\a\1\s\tests\Integration\DSC_SqlLogin.Integration.Tests.ps1: line 98
2020-11-21T11:11:24.3455255Z       [-] Should have set the resource and all the parameters should match 29ms
2020-11-21T11:11:24.3494829Z         Expected 'Present', but got $null.
2020-11-21T11:11:24.3517690Z         109:                 $resourceCurrentState.Ensure | Should -Be 'Present'
2020-11-21T11:11:24.3553176Z         at <ScriptBlock>, D:\a\1\s\tests\Integration\DSC_SqlLogin.Integration.Tests.ps1: line 109

**Comment by johlju** [comment]
I will rerun test, but can't do it until the unit tests has ran. Waiting for that.

I think the problem is the tests run too fast and the build worker can't keep up sometimes. Something doesn't return to the correct state fast enough. It was better after adding `Wait-ForIdleLcm` but still see those issues. Might help if we pasue a bit longer after LCM becomes idle. 🤔  

https://github.com/dsccommunity/SqlServerDsc/blob/56ebcfe60cb35e7abae2ac32f69cf49ab6e01887/tests/TestHelpers/CommonTestHelper.psm1#L395-L406

**Comment by johlju** [comment]
Maybe we should call `Clear-DscLcmConfiguration` inside `Wait-ForIdleLcm`. 🤔  It is normally run at the end of the tests, but those tests that run multiple integration tests might need top have after each test. 🤔 
https://github.com/dsccommunity/DscResource.Test/blob/619249435884093da51d9316e07073d573975154/source/Public/Clear-DscLcmConfiguration.ps1 

Adding an issue for this.

**Comment by Fiander** [comment]
When the build fails, it is always on SqlLogin.

To me, in the test this part is scary: row 39-43 
        <#
            This will install dependencies using other resource modules, and is
            done without running extra tests on the result.
            This is done to speed up testing.
        #>

To me this reads as: were adding logins in an other resource module that we are now depended on.
Could it be possible the tests of other modules are now already been cleaned up sometimes and because of that we randomly have these issues?

**Comment by johlju** [comment]
That configuration creates local users and groups on the build worker which are then used in the tests for SqlLogin. The text mean that we do not run Get-DscConfiguration or Test-DscConfiguration for that configuration. I think that text could have been worded differently. 🙂

**Comment by johlju** [comment]
It is documented here what is left behind by this test, and if something is removed then the tests should fail with other error messages.
https://github.com/dsccommunity/SqlServerDsc/blob/master/tests/Integration/README.md#sqllogin

The error messages we are seeing I think is the LCM that is having issues.

**Pull request merged**
