### PR TITLE
SqlAlwaysOnService: Get-TargetResource does not return all the schema properties

### LINKED ISSUE #1501: SqlAlwaysOnService: Get-TargetResource does not return all the schema properties
The resource SqlAlwaysOnService should return all the properties from Get-TargetResource that are specified in the schema.mof.

### PR DESCRIPTION
**Pull request by awickham10**
#### Pull Request (PR) description
Modify SqlAlwaysOnService Get-TargetResource to return all properties that are defined in the MOF.

#### This Pull Request (PR) fixes the following issues
Fixes #1501.

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation updated in the resource's README.md.
- [ ] Resource parameter descriptions updated in schema.mof.
- [x] Comment-based help updated, including parameter descriptions.
- [ ] Localization strings updated.
- [ ] Examples updated.
- [x] Unit tests updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Code changes adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1618)

### CODE REVIEW

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1618#-:-MIcFmVy5kw-rXHNN8sw:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by johlju** [comment]
@awickham10 this looks good. Would you mind also updating the unit test as well to tests that these properties are actually returning with the expected values? 

https://github.com/dsccommunity/SqlServerDsc/blob/4a425ead398d67e4b616720e095b7ab885e9fb82/tests/Unit/DSC_SqlAlwaysOnService.Tests.ps1#L61

**Comment by awickham10** [comment]
> @awickham10 this looks good. Would you mind also updating the unit test as well to tests that these properties are actually returning with the expected values?
> 
> https://github.com/dsccommunity/SqlServerDsc/blob/4a425ead398d67e4b616720e095b7ab885e9fb82/tests/Unit/DSC_SqlAlwaysOnService.Tests.ps1#L61

Changes incoming for that. I used the same style from SqlDatabase. Side note - are any one of these resources the "gold standard" to look at when working on other resources as far as style/preferred logic/etc.?

**Comment by johlju** [comment]
> Side note - are any one of these resources the "gold standard" to look at when working on other resources as far as style/preferred logic/etc.?

All the resources are more or less following the style guideline, but I would say the resource `SqlDatabaseObjectPermission` is the one that uses the lastest patterns that resources (especially new ones) should adopt.

**Comment by awickham10** [comment]
> > Side note - are any one of these resources the "gold standard" to look at when working on other resources as far as style/preferred logic/etc.?
> 
> All the resources are more or less following the style guideline, but I would say the resource `SqlDatabaseObjectPermission` is the one that uses the lastest patterns that resources (especially new ones) should adopt.

Great, thank you!

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1618#-:-MIeDxAT9NVhq_tbGABN:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
