### PR TITLE
SqlMemory: Allow setting of dynamic value for min server memory #1397

### LINKED ISSUE #1397: SqlMemory: Allow setting of dynamic value for min server memory.
#### Details of the scenario you tried and the problem that is occurring
Setting a discrete value for min server memory rather than dynamically calculating it adds overhead when managing generic configurations that are applied to many servers. I have a baseline configuration that goes out with all servers. Currently I leave Min Server Memoryh to the default rathe than set a value in the configuration.

#### Verbose logs showing the problem
N/A

#### Suggested solution to the issue
Allow for a dynamic calcualtion of min server memory based on a specific percentage of the max server memory value (discrete or dynamically calculated).

If I have a server with 128 GB of RAM and have a max server memory value of 105GB, I then want to say that I want a min server memory value that is 35% of the max server memory value so it should be calculated and set to ~36GB. 

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
N/A
```

#### SQL Server edition and version the target node is running
SQL 2016 & 2017 

#### SQL Server PowerShell modules present on the target node
N/A

#### The operating system the target node is running
Windows server 2016 & 2019

#### Version and build of PowerShell the target node is running
5.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
13.0.0.0

### PR DESCRIPTION
**Pull request by TrisBits**
#### Pull Request (PR) description

- SqlMemory
  - Added two new optional parameters MinMemoryPercent and MaxMemoryPercent.
    Provides the ability to set the minimum and/or maximum buffer pool used by
    the SQL Server instance as a percentage of total server memory (issue #1397).

#### This Pull Request (PR) fixes the following issues
- Fixes #1397 

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation updated in the resource's README.md.
- [x] Resource parameter descriptions updated in schema.mof.
- [x] Comment-based help updated, including parameter descriptions.
- [x] Localization strings updated.
- [x] Examples updated.
- [x] Unit tests updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Code changes adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1695)

### CODE REVIEW

**Comment by TrisBits** [comment]
@johlju  Not to worry, I completely understand.  Thank you for the update and I look forward to your review and feedback :)

**Comment by johlju** [comment]
This is still on the todo list. Just a lot of work getting DnsServerDsc out the door. I will swing back here soon. I will try to get to the backlog of all reviews during Easter.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1695#-:-MYVDWPY4ddNPmDEoLdW:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @TrisBits)

**Review by johlju — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1695)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @TrisBits)

**Comment by johlju** [comment]
@TrisBits sorry it took so long - been working on tooling and other modules for a while. This looks great! Awesome work on the tests! 😃

**Comment by TrisBits** [comment]
@johlju Thank you for the code review and feedback.  Not to worry about the delay, you have a lot on your plate.

**Pull request merged**
