### PR TITLE
SqlServerDsc: Resources work with automatic seeding

### LINKED ISSUE #487: SqlAGReplica: Support automatic seeding
**Details of the scenario you try and problem that is occurring:**
xSQLServerAlwaysOnAvailabilityGroupReplica resource does not set the seeding_mode property in SQL 2016. This needs to be set to support automatic seeding.

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
all

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
dev

### PR DESCRIPTION
**Pull request by Sidoran**
#### Pull Request (PR) description
- SqlAg
  - Added optional parameter `SeedingMode` that will set the SeedingMode for the SQL
    Server 2016 and higher. This parameter can only be used together with the
    module _SqlServer_ installed (tested  v21.0.17099). The parameter will be
    ignored if SQLPS module will be used.
- SqlAgReplica
  - Added optional parameter `SeedingMode` that will set the SeedingMode for the SQL
    Server 2016 and higher.  This parameter can only be used together with the
    module _SqlServer_ installed (tested  v21.0.17099). The parameter will be
    ignored if SQLPS module will be used.

#### This Pull Request (PR) fixes the following issues
- Fixes #487

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation updated in the resource's README.md.
- [x] Resource parameter descriptions updated in schema.mof.
- [x] Comment-based help updated, including parameter descriptions.
- [ ] Localization strings updated.
- [ ] Examples updated.
- [x] Unit tests updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Code changes adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1915)

### CODE REVIEW

**Comment by Sidoran** [comment]
Hi @johlju, can you please look at PR? Can you please also rerun the verification pipeline because two agents stopped to respond, and the whole pipeline marked as failed?

**Review by johlju — CHANGES_REQUESTED** [review]
I just made.a quick review and found some thing you can start with. Need to do more review. I only commented on the first code file, but the same comments are for the other as well.

> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1915#-:-NTTs27EAlQPKWn1BeFm:b9e3mr6)* status: 1 of 6 files reviewed, 5 unresolved discussions (waiting on @Sidoran)

___
*[`CHANGELOG.md` line 54 at r3](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1915#-NTTiZTp5SDjPj0ANAoZ:-NTTiZTp5SDjPj0ANAo_:b5tjvpy) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/176b7a06cebe53b5e0c7d5506094ccf4c578b7d2/CHANGELOG.md#L54)):*
> ```Markdown
>     (tested v21.0.17099). The parameter will be ignored if SQLPS module will be
>     used.
> >>>>>>> upstream/main
> ```

This seems to have been leftover.



_Code quote:_
```Markdown
>>>>>>> upstream/main
```
___
*[`source/DSCResources/DSC_SqlAG/DSC_SqlAG.psm1` line 99 at r3](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1915#-NTTmV692ganu_CtTfdH:-NTTmV692ganu_CtTfdI:b8bsnuv) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/176b7a06cebe53b5e0c7d5506094ccf4c578b7d2/source/DSCResources/DSC_SqlAG/DSC_SqlAG.psm1#L99)):*
> ```PowerShell
>             $alwaysOnAvailabilityGroupResource.Add('DatabaseHealthTrigger', $availabilityGroup.DatabaseHealthTrigger)
>             $alwaysOnAvailabilityGroupResource.Add('DtcSupportEnabled', $availabilityGroup.DtcSupportEnabled)
>             if ( $sqlModuleName -eq 'SQLServer' )
> ```

We should always return this property, either with a value or $null.



_Code quote:_
```PowerShell
            if ( $sqlModuleName -eq 'SQLServer' )
            {
                $alwaysOnAvailabilityGroupResource.Add('SeedingMode', $availabilityGroup.AvailabilityReplicas[$serverObject.DomainInstanceName].SeedingMode)
            }
```
___
*[`source/DSCResources/DSC_SqlAG/DSC_SqlAG.psm1` line 359 at r3](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1915#-NTTkKY1AWiBdD4WLT-6:-NTTkKY1AWiBdD4WLT-7:b-ryefsd) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/176b7a06cebe53b5e0c7d5506094ccf4c578b7d2/source/DSCResources/DSC_SqlAG/DSC_SqlAG.psm1#L359)):*
> ```PowerShell
>                 }
> 
>                 if ( ( $sqlMajorVersion -ge 13 ) -and ( $sqlModuleName -eq 'SQLServer' ) )
> ```

If there is a chance that the command not always has the parameter then it would be better to check if the actual command supports the parameter. So here we can do this instead:
```
(Get-Command -Name 'New-SqlAvailabilityReplica').Parameters.ContainsKey('SeedingMode')
```



_Code quote:_
```PowerShell
if ( ( $sqlMajorVersion -ge 13 ) -and ( $sqlModuleName -eq 'SQLServer' ) )
```
___
*[`source/DSCResources/DSC_SqlAG/DSC_SqlAG.psm1` line 524 at r3](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1915#-NTTr8OB3hZalhnvwk11:-NTTr8OB3hZalhnvwk12:borztle) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/176b7a06cebe53b5e0c7d5506094ccf4c578b7d2/source/DSCResources/DSC_SqlAG/DSC_SqlAG.psm1#L524)):*
> ```PowerShell
>                 }
> 
>                 if ( ( $submittedParameters -contains 'SeedingMode' ) -and ( $sqlMajorVersion -ge 13 ) -and ( $SeedingMode -ne $availabilityGroup.AvailabilityReplicas[$serverObject.DomainInstanceName].SeedingMode ) -and ( $sqlModuleName -eq 'SQLServer' ) )
> ```

Could we split the if-statement into at least two to make it easier to read? For example first check if seeding mode should be enforce, then if it is correct version and the property exist.



_Code quote:_
```PowerShell
if ( ( $submittedParameters -contains 'SeedingMode' ) -and ( $sqlMajorVersion -ge 13 ) -and ( $SeedingMode -ne $availabilityGroup.AvailabilityReplicas[$serverObject.DomainInstanceName].SeedingMode ) -and ( $sqlModuleName -eq 'SQLServer' ) )
```
___
*[`source/DSCResources/DSC_SqlAG/DSC_SqlAG.psm1` line 524 at r3](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1915#-NTTrFwZCauKZ7Bc5ttC:-NTTrFwZCauKZ7Bc5ttD:b-fhzn2v) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/176b7a06cebe53b5e0c7d5506094ccf4c578b7d2/source/DSCResources/DSC_SqlAG/DSC_SqlAG.psm1#L524)):*
> ```PowerShell
>                 }
> 
>                 if ( ( $submittedParameters -contains 'SeedingMode' ) -and ( $sqlMajorVersion -ge 13 ) -and ( $SeedingMode -ne $availabilityGroup.AvailabilityReplicas[$serverObject.DomainInstanceName].SeedingMode ) -and ( $sqlModuleName -eq 'SQLServer' ) )
> ```

If there is a chance that the type does not contain the property, we should check for that instead of looking for the module name. Like:
```
($availabilityGroup.AvailabilityReplicas[$serverObject.DomainInstanceName] | Get-Member  -MemberType Property).Name -contains 'SeedingMode'
```



_Code quote:_
```PowerShell
$sqlModuleName -eq 'SQLServer'
```

**Comment by Sidoran** [comment]
@johlju, I made the changes according to your comments.
The only thing confusing me is the code responsible for the Get, Update (inside Set), and Test using Microsoft.SqlServer.Management.Smo.Server object which supports SeedingMode for all SQL 2016 and newer. The only issue I have is the New-SQLAvailabilityReplica command in SQLPS module does not support SeedingMode parameters. And that's why I have to use the if ( (Get-Command -Name 'New-SqlAvailabilityReplica').Parameters.ContainsKey('SeedingMode') ) in all places. If you will have some idea how to get rid of this check I would be happy to rewrite this part of the code.

**Comment by johlju** [comment]
> If you will have some idea how to get rid of this check I would be happy to rewrite this part of the code.

Only way is to connect to the replica (e.g. `Connect-SqlDscDatabaseEngine` to get the `Server` object. The set the `SeedingMode` property on the right object. But that might be a bigger (too big?) change?

**Review by johlju — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 1 of 1 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1915)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Sidoran)

**Review by johlju — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1915)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @Sidoran)

___
*[`source/DSCResources/DSC_SqlAG/DSC_SqlAG.psm1` line 359 at r5](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1915#-NU1t98r3KLNkNzP-D2k:-NU1t98s1eSkCjWBeXwV:b-thyll) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/57012763e6e84677b456becaf6dde582f9dda736/source/DSCResources/DSC_SqlAG/DSC_SqlAG.psm1#L359)):*
> ```PowerShell
>                 }
> 
>                 if ( ( $sqlMajorVersion -ge 13 ) -and (Get-Command -Name 'New-SqlAvailabilityReplica').Parameters.ContainsKey('SeedingMode') )
> ```

Instead of having this check, I thing we should have this check one time at the beginning of the Set-method. If the user passes SeedingMode and version is lower than 13 then it should throw an exception saying that "using SeedingMode for verison lower than 13 is not supported".



_Code quote:_
```PowerShell
$sqlMajorVersion -ge 13
```

**Review by johlju — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1915)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @Sidoran)

*[a discussion](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1915#-NU1tZ6A8_AdX6ltYg1B:-NU1tZ6A8_AdX6ltYg1C:b-im6256) (no related file):*
Is it possible for you to add unit tests to cover the changed (added) code paths?

___

**Comment by Sidoran** [comment]
<details><summary>
Previously, johlju (Johan Ljunggren) wrote…
</summary>

> > _[Reviewable](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1915)_ status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @Sidoran)
> 
> _[`source/DSCResources/DSC_SqlAG/DSC_SqlAG.psm1` line 359 at r5](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1915#-NU1t98r3KLNkNzP-D2k:-NU1t98s1eSkCjWBeXwV:b-thyll) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/57012763e6e84677b456becaf6dde582f9dda736/source/DSCResources/DSC_SqlAG/DSC_SqlAG.psm1#L359)):_
> 
> > ```powershell
> >                 }
> > 
> >                 if ( ( $sqlMajorVersion -ge 13 ) -and (Get-Command -Name 'New-SqlAvailabilityReplica').Parameters.ContainsKey('SeedingMode') )
> > ```
> 
> Instead of having this check, I thing we should have this check one time at the beginning of the Set-method. If the user passes SeedingMode and version is lower than 13 then it should throw an exception saying that "using SeedingMode for verison lower than 13 is not supported".
> 
> _Code quote:_
> 
> ```powershell
> $sqlMajorVersion -ge 13
> ```


</details>


The Major version check at the beginning will break the current behavior for the _BasicAvailabilityGroup_, _DatabaseHealthTrigger_ and _DtcSupportEnabled_ availability group options. 

<details><summary>
Previously, johlju (Johan Ljunggren) wrote…
</summary>
> Is it possible for you to add unit tests to cover the changed (added) code paths?
</details>

I've already made some unit test modifications for the SqlAGReplica resource. The SqlAg, as I see, is uncovered by pester because of migration to Pester 5.x
<details><summary>
Previously, johlju (Johan Ljunggren) wrote…
</summary>
> Only way is to connect to the replica (e.g. `Connect-SqlDscDatabaseEngine` to get the `Server` object. The set the `SeedingMode` property on the right object. But that might be a bigger (too big?) change?
</details>

Sorry, I didn't get your Idea. The `Connect-SqlDscDatabaseEngine` will work with the `SeedingMode` because it uses the `Connect-SQL`, which uses the SMO object. 
IMHO, the problem is in the New-SqlAvailabilityReplica command that has the SeedingMode parameter in the SQLServer module and doesn't have it in the case of SQLPS(which is the default).

**Comment by johlju** [comment]
> The Major version check at the beginning will break the current behavior for the BasicAvailabilityGroup, DatabaseHealthTrigger and DtcSupportEnabled availability group options.

I haven’t look at the code so not sure, but I meant: “if major version is less than 13 and PSBoundParameters contain SeedingMode then throw an exception telling the user to not specify SeedingMode as it is not supported”. I might be wrong but I thought you had that check because it was supported in lower major versions?

**Comment by johlju** [comment]
> Sorry, I didn't get your Idea. The Connect-SqlDscDatabaseEngine will work with the SeedingMode because it uses the Connect-SQL, which uses the SMO object.
IMHO, the problem is in the New-SqlAvailabilityReplica command that has the SeedingMode parameter in the SQLServer module and doesn't have it in the case of SQLPS(which is the default).

I meant set all the settings using the SMO objects directly (if possible) and not use any commands from either module. It was the only way around that the Microsoft SQL Server Team has not added the parameter to the command in the module SQLPS. 

But I’m good with the current way of checking for the parameter you added. Though maybe we should have outputted a warning message telling the user that they should use the module SqlServer if they pass the parameter SeedingMode. 🤔

**Comment by johlju** [comment]
> I've already made some unit test modifications for the SqlAGReplica resource. The SqlAg, as I see, is uncovered by pester because of migration to Pester 5.x

Yes, no need to add unit tests for SqlAg if it hasn’t been converted. It probably need to be heavily refactored then anyway.

**Comment by Sidoran** [comment]
> I haven’t look at the code so not sure, but I meant: “if major version is less than 13 and PSBoundParameters contain SeedingMode then throw an exception telling the user to not specify SeedingMode as it is not supported”. I might be wrong but I thought you had that check because it was supported in lower major versions?

Auto seeding was introduced in SQL 2016. When I did changes, I was based on existing behavior in a code, as you may see here
https://github.com/dsccommunity/SqlServerDsc/blob/a86039c2ae0bdde6b7e479d529918adc11f3296c/source/DSCResources/DSC_SqlAG/DSC_SqlAG.psm1#L367-L372. As far as I understand, this was a conscious decision not to throw an exception in case you try to use a property from SQL 2016 in an older version.

**Comment by johlju** [comment]
> When I did changes, I was based on existing behavior in a code

Ah, I see. Then we continue on the same path.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1915#-:-NU8HkvuAOs5yERCN-Rn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Sidoran)

**Comment by johlju** [comment]
@Sidoran this is ready to merge but got an issue with the pipeline unrelated to this PR. Trying to fix it so I can merge this.

**Review by johlju — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1915)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Sidoran)

**Pull request merged**
