### PR TITLE
BREAKING CHANGE: SqlScript, SqlScriptQuery - Add new key 'Id' to allow reuse of a script with different variables

### LINKED ISSUE #596: SqlScript: complains about duplicates when reusing scripts
**Details of the scenario you try and problem that is occurring:**
I am using an xSQLServerScript to restore four databases.  After perfecting the first one, i am unable to reuse the scripts in their entirety.

Now, i am trying to run this four different times, changing the name of each section and the variable i am using to pass the parameters.  I see no reason that i cannot reuse the scripts as i have written them to be generic enough to pass unique information each time i change the variables.

But right now, the only way I can make this work is to copy and paste the test file script and rename it for each new database I restore.

Here is the TSQL script I am using:

`RESTORE DATABASE [$(TSQL_DB)] FROM DISK = '$(TSQL_SRC)'
WITH 
MOVE '$(TSQL_DATA)' TO '$(TSQL_DATA_FILE)', 
MOVE '$(TSQL_LOG)' TO '$(TSQL_LOG_FILE)', 
RECOVERY, REPLACE, STATS = 10;
`

If these keys are required, then I propose a fifth key to allow the uniqueness to be defined.

**The DSC configuration that is using the resource:**

        xSQLServerScript RestoreDB {
            ServerInstance       = "localhost"
            SetFilePath          = "C:\source\sqlscripts\xScript_CreateDBFromBackup.sql"
            TestFilePath         = "c:\source\sqlscripts\xScript_TestForBackup.sql"
            GetFilePath          = "c:\source\sqlscripts\xScript_TestForBackup.sql"
            Variable             = $Node.RestoreDBParms
            PsDSCRunasCredential = $Node.LocalAdminAccount
            DependsOn            = "[File]RestoreBackupFile"
        }

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows 2012 R2 with WMF 5.1

**Version of the DSC module you're using:**
xSQLServer 7.1.0.0

### PR DESCRIPTION
**Pull request by Borgquite**
#### Pull Request (PR) description

Per discussion in #596 and on #DSC channel, add new key 'Id' to SqlScript, SqlScriptQuery resources, replacing 'InstanceName' and the script variables, allowing reuse of a script with different variables.

#### This Pull Request (PR) fixes the following issues

- Fixes #596
- Also updates unit tests for SqlScript and SqlScriptQuery - so that the Set test with timeout actually tests as it should

#### Task list
- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [x] Resource documentation updated in the resource's README.md.
- [x] Resource parameter descriptions updated in schema.mof.
- [x] Comment-based help updated, including parameter descriptions.
- [ ] Localization strings updated.
- [x] Examples updated.
- [x] Unit tests updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Integration tests updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Code changes adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2043)

### CODE REVIEW

**Review by Borgquite — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2043)* status: 17 of 21 files reviewed, 11 unresolved discussions (waiting on @dan-hughes and @johlju)

___
*[`source/DSCResources/DSC_SqlScript/DSC_SqlScript.schema.mof` line 5 at r1](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2043#-O44sPmI7KCrQFbFKpTv:-O45hzMQ9OiKCbHFQrDx:b-896fix) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/ef51ce7a96cc35562e30669981c67fe0e4f73961/source/DSCResources/DSC_SqlScript/DSC_SqlScript.schema.mof#L5)):*
<details><summary><i>Previously, dan-hughes (Daniel Hughes) wrote…</i></summary><blockquote>

Keep the existing Key properties, this then allows some flexibility on the Id not having to be unique across the whole MOF.
</blockquote></details>

Done.
___
*[`source/DSCResources/DSC_SqlScript/DSC_SqlScript.schema.mof` line 6 at r1](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2043#-O44t8yGElbbUxH1-bkh:-O45hzhe1nmRaG0hB7Yj:b-896fix) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/ef51ce7a96cc35562e30669981c67fe0e4f73961/source/DSCResources/DSC_SqlScript/DSC_SqlScript.schema.mof#L6)):*
<details><summary><i>Previously, dan-hughes (Daniel Hughes) wrote…</i></summary><blockquote>

See above.
</blockquote></details>

Done.
___
*[`source/DSCResources/DSC_SqlScript/DSC_SqlScript.schema.mof` line 7 at r1](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2043#-O44tBuSBoOIdB0BN0Lv:-O45i-9y3rBv-wGwUDhe:b-896fix) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/ef51ce7a96cc35562e30669981c67fe0e4f73961/source/DSCResources/DSC_SqlScript/DSC_SqlScript.schema.mof#L7)):*
<details><summary><i>Previously, dan-hughes (Daniel Hughes) wrote…</i></summary><blockquote>

See above.
</blockquote></details>

Done.
___
*[`source/DSCResources/DSC_SqlScript/DSC_SqlScript.schema.mof` line 8 at r1](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2043#-O44tF0D7LDRRXRFtu7H:-O45i-Rm9zDbvc4Pq7-5:b-896fix) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/ef51ce7a96cc35562e30669981c67fe0e4f73961/source/DSCResources/DSC_SqlScript/DSC_SqlScript.schema.mof#L8)):*
<details><summary><i>Previously, dan-hughes (Daniel Hughes) wrote…</i></summary><blockquote>

See above.
</blockquote></details>

Done.
___
*[`source/DSCResources/DSC_SqlScriptQuery/DSC_SqlScriptQuery.schema.mof` line 4 at r1](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2043#-O44tR2U652l1nS88OO8:-O45i0of89IUd7kYVq6d:b-896fix) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/ef51ce7a96cc35562e30669981c67fe0e4f73961/source/DSCResources/DSC_SqlScriptQuery/DSC_SqlScriptQuery.schema.mof#L4)):*
<details><summary><i>Previously, dan-hughes (Daniel Hughes) wrote…</i></summary><blockquote>

See Dsc_SqlScript.
</blockquote></details>

Done.
___
*[`source/DSCResources/DSC_SqlScriptQuery/DSC_SqlScriptQuery.schema.mof` line 5 at r1](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2043#-O44tTx2CGYVjgFlbhWz:-O45i1II1eu68Of3k5rz:b-896fix) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/ef51ce7a96cc35562e30669981c67fe0e4f73961/source/DSCResources/DSC_SqlScriptQuery/DSC_SqlScriptQuery.schema.mof#L5)):*
<details><summary><i>Previously, dan-hughes (Daniel Hughes) wrote…</i></summary><blockquote>

See Dsc_SqlScript.
</blockquote></details>

Done.
___
*[`source/DSCResources/DSC_SqlScriptQuery/DSC_SqlScriptQuery.schema.mof` line 6 at r1](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2043#-O44tUgo4fMicNCWYdP7:-O45i1bIE74ogek9PbpG:b-896fix) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/ef51ce7a96cc35562e30669981c67fe0e4f73961/source/DSCResources/DSC_SqlScriptQuery/DSC_SqlScriptQuery.schema.mof#L6)):*
<details><summary><i>Previously, dan-hughes (Daniel Hughes) wrote…</i></summary><blockquote>

See Dsc_SqlScript.
</blockquote></details>

Done.
___
*[`source/DSCResources/DSC_SqlScriptQuery/DSC_SqlScriptQuery.schema.mof` line 7 at r1](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2043#-O44tZNsCWSCQ_MP4jhf:-O45i1th4Ut8DIDQICNR:bb6un1j) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/ef51ce7a96cc35562e30669981c67fe0e4f73961/source/DSCResources/DSC_SqlScriptQuery/DSC_SqlScriptQuery.schema.mof#L7)):*
<details><summary><i>Previously, dan-hughes (Daniel Hughes) wrote…</i></summary><blockquote>

See Dsc_SqlScript.
</blockquote></details>

Done
___
*[`source/DSCResources/DSC_SqlScriptQuery/DSC_SqlScriptQuery.schema.mof` line 8 at r1](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2043#-O44t_ceDTqkjwJzgesZ:-O45i2Gf4RZ8Lo_uv6SF:b-896fix) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/ef51ce7a96cc35562e30669981c67fe0e4f73961/source/DSCResources/DSC_SqlScriptQuery/DSC_SqlScriptQuery.schema.mof#L8)):*
<details><summary><i>Previously, dan-hughes (Daniel Hughes) wrote…</i></summary><blockquote>

See Dsc_SqlScript.
</blockquote></details>

Done.
___
*[`tests/Unit/DSC_SqlScript.Tests.ps1` line 222 at r1](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2043#-O44yTmY9zXhwu0bp4x-:-O45i5yq6HmEYgGiB3qT:b-gfblik) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/ef51ce7a96cc35562e30669981c67fe0e4f73961/tests/Unit/DSC_SqlScript.Tests.ps1#L222)):*
<details><summary><i>Previously, dan-hughes (Daniel Hughes) wrote…</i></summary><blockquote>

You do not need to create a new object here, just reuse `$mockSetParametersTimeout` and update and values as required.
</blockquote></details>

Understood - mainly just copying the existing Get and Test resources code - so fixed them too...
___
*[`tests/Unit/DSC_SqlScriptQuery.Tests.ps1` line 222 at r1](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2043#-O44ykPu6_IG5n8REAVF:-O45iM38CyOFP1Z7yiHK:b-896fix) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/ef51ce7a96cc35562e30669981c67fe0e4f73961/tests/Unit/DSC_SqlScriptQuery.Tests.ps1#L222)):*
<details><summary><i>Previously, dan-hughes (Daniel Hughes) wrote…</i></summary><blockquote>

Same as Set tests,no need to create a new object here, just reuse `$mockTestParametersTimeout` and update and values as required.
</blockquote></details>

Done.

**Review by dan-hughes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2043)* status: 17 of 21 files reviewed, 10 unresolved discussions (waiting on @Borgquite and @johlju)

___
*[`tests/Unit/DSC_SqlScript.Tests.ps1` line 132 at r2](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2043#-O46DAywEOk-gtNM_WlB:-O46DAywEOk-gtNM_WlC:bc1zhnx) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/da90e1006529b4c81b3137824224d909f017cdde/tests/Unit/DSC_SqlScript.Tests.ps1#L132)):*
> ```PowerShell
>                 Set-StrictMode -Version 1.0
> 
>                 $mockTestParametersTimeout = $mockDefaultParameters.Clone()
> ```

You do not need to clone again, you already have a fresh instance from the `BeforeEach`. Just set the timeout value on `$mockGetTargetParameters`.
___
*[`tests/Unit/DSC_SqlScript.Tests.ps1` line 215 at r2](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2043#-O46F7zrEEKxa95pt8NH:-O46F7zrEEKxa95pt8NI:b-34vmyd) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/da90e1006529b4c81b3137824224d909f017cdde/tests/Unit/DSC_SqlScript.Tests.ps1#L215)):*
> ```PowerShell
>                 Set-StrictMode -Version 1.0
> 
>                 $mockTestParametersTimeout = $mockDefaultParameters.Clone()
> ```

See above
___
*[`tests/Unit/DSC_SqlScript.Tests.ps1` line 291 at r2](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2043#-O46F9MvABDPScGAB7rf:-O46F9MwAlkiEmJFC8Bj:b-34vmyd) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/da90e1006529b4c81b3137824224d909f017cdde/tests/Unit/DSC_SqlScript.Tests.ps1#L291)):*
> ```PowerShell
>                     Set-StrictMode -Version 1.0
> 
>                     $mockTestParametersTimeout = $mockDefaultParameters.Clone()
> ```

See above
___
*[`tests/Unit/DSC_SqlScript.Tests.ps1` line 314 at r2](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2043#-O46FAVy01VrVVfvyBMI:-O46FAVy01VrVVfvyBMJ:b-34vmyd) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/da90e1006529b4c81b3137824224d909f017cdde/tests/Unit/DSC_SqlScript.Tests.ps1#L314)):*
> ```PowerShell
>                     Set-StrictMode -Version 1.0
> 
>                     $mockTestParametersTimeout = $mockDefaultParameters.Clone()
> ```

See above
___
*[`tests/Unit/DSC_SqlScriptQuery.Tests.ps1` line 132 at r2](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2043#-O46FBc-1iMBGpXTctiX:-O46FBc-1iMBGpXTctiY:b-34vmyd) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/da90e1006529b4c81b3137824224d909f017cdde/tests/Unit/DSC_SqlScriptQuery.Tests.ps1#L132)):*
> ```PowerShell
>                 Set-StrictMode -Version 1.0
> 
>                 $mockTestParametersTimeout = $mockDefaultParameters.Clone()
> ```

See above
___
*[`tests/Unit/DSC_SqlScriptQuery.Tests.ps1` line 215 at r2](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2043#-O46FD0M8aBb2Pqu7wcF:-O46FD0M8aBb2Pqu7wcG:b-34vmyd) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/da90e1006529b4c81b3137824224d909f017cdde/tests/Unit/DSC_SqlScriptQuery.Tests.ps1#L215)):*
> ```PowerShell
>                 Set-StrictMode -Version 1.0
> 
>                 $mockTestParametersTimeout = $mockDefaultParameters.Clone()
> ```

See above
___
*[`tests/Unit/DSC_SqlScriptQuery.Tests.ps1` line 291 at r2](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2043#-O46FEvR0-cQeiP1lzCj:-O46EMN3CRuZTP5CHIDf:b-q64pkt) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/da90e1006529b4c81b3137824224d909f017cdde/tests/Unit/DSC_SqlScriptQuery.Tests.ps1#L291)):*
> ```PowerShell
>                     Set-StrictMode -Version 1.0
> 
>                     $mockTestParametersTimeout = $mockDefaultParameters.Clone()
> ```

See above.
___
*[`tests/Unit/DSC_SqlScriptQuery.Tests.ps1` line 314 at r2](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2043#-O46FGCe3wwMIWFNVn7F:-O46FGCe3wwMIWFNVn7G:b-q64pkt) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/da90e1006529b4c81b3137824224d909f017cdde/tests/Unit/DSC_SqlScriptQuery.Tests.ps1#L314)):*
> ```PowerShell
>                     Set-StrictMode -Version 1.0
> 
>                     $mockTestParametersTimeout = $mockDefaultParameters.Clone()
> ```

See above.

**Review by dan-hughes — COMMENTED** [review]
> Reviewed 2 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2043)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johlju)

**Comment by johlju** [comment]
Great work all of you! 🙂

**Pull request merged**
