### PR TITLE
BREAKING CHANGE: SqlScript, SqlScriptQuery - Variable as key to allow reuse of a script with different variables

### LINKED ISSUE #596: SqlScript: complains about duplicates when reusing scripts
**Details of the scenario you try and problem that is occurring:**
I am using an xSQLServerScript to restore four databases.  After perfecting the first one, i am unable to reuse the scripts in their entirety.

Now, i am trying to run this four different times, changing the name of each section and the variable i am using to pass the parameters.  I see no reason that i cannot reuse the scripts as i have written them to be generic enough to pass unique information each time i change the variables.

But right now, the only way I can make this work is to copy and paste the test file script and rename it for each new database I restore.

Here is the TSQL script I am using:

`RESTORE DATABASE [$(TSQL_DB)] FROM DISK = '$(TSQL_SRC)'
WITH 
MOVE '$(TSQL_DATA)' TO '$(TSQL_DATA_FILE)', 
MOVE '$(TSQL_LOG)' TO '$(TSQL_LOG_FILE)', 
RECOVERY, REPLACE, STATS = 10;
`

If these keys are required, then I propose a fifth key to allow the uniqueness to be defined.

**The DSC configuration that is using the resource:**

        xSQLServerScript RestoreDB {
            ServerInstance       = "localhost"
            SetFilePath          = "C:\source\sqlscripts\xScript_CreateDBFromBackup.sql"
            TestFilePath         = "c:\source\sqlscripts\xScript_TestForBackup.sql"
            GetFilePath          = "c:\source\sqlscripts\xScript_TestForBackup.sql"
            Variable             = $Node.RestoreDBParms
            PsDSCRunasCredential = $Node.LocalAdminAccount
            DependsOn            = "[File]RestoreBackupFile"
        }

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows 2012 R2 with WMF 5.1

**Version of the DSC module you're using:**
xSQLServer 7.1.0.0

### PR DESCRIPTION
**Pull request by Borgquite**
#### Pull Request (PR) description
Add 'Variable' as a key to SqlScript, SqlScriptQuery resources to allow reuse of a script with different variables

#### This Pull Request (PR) fixes the following issues

- Fixes #596
- Also updates unit tests for SqlScript and SqlScriptQuery - so that the Set test with timeout actually tests as it should

#### Task list
- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation updated in the resource's README.md.
- [x] Resource parameter descriptions updated in schema.mof.
- [x] Comment-based help updated, including parameter descriptions.
- [ ] Localization strings updated.
- [x] Examples updated.
- [x] Unit tests updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Integration tests updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Code changes adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2042)

### CODE REVIEW

**Comment by Borgquite** [comment]
I'm having a go at this, but at the moment I'm struggling to get HQRM tests to pass. Is it possible that it's not permitted to use a String[] as a Key variable (quite likely?)

If that's the case, perhaps what is needed is a new Key variable called something like 'Id' or 'Name' - and the existing Keys (InstanceName, SetFilePath, GetFilePath, TestFilePath) could be removed as Keys. That might remove some of the compile-time protections against idempotency but would open up the opportunity to reuse a script file multiple times with just the variables needing changing.

**Comment by dan-hughes** [comment]
I believe you are correct, Key properties need to be 'simple'. I can't find where it's documented though.

Why would not adding another Key property like you mention not work?

Would there be a situation where the database name would be a Key parameter but used as a variable? Or would the same scripts be reused against the same database?

**Comment by Borgquite** [comment]
As discussed on the #dsc channel, I'll redo this patch with a new Key parameter which should allow us to do this. It will be a breaking change but we've agreed that is pretty unavoidable in the circumstances.

**Comment by Borgquite** [comment]
Opened new pull request at #2043

**Pull request closed without merging**
