### PR TITLE
SqlDatabaseUserRole: New resource

### PR DESCRIPTION
**Pull request by Rob-S**
#### Pull Request (PR) description
New resource that allows managing the roles assigned to a user or group.

#### This Pull Request (PR) fixes the following issues
New Resource #1488

#### Task list
- [✓] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [✓ ] Resource documentation added/updated in README.md.
- [ ✓] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ✓] Comment-based help added/updated.
- [ ✓] Localization strings added/updated in all localization files as appropriate.
- [ ✓] Examples appropriately added/updated.
- [ ✓] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
          Some unit tests may need to be commented out.
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ✓] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1489)

### CODE REVIEW

**Comment by Rob-S** [comment]
The Build received an error: "ERROR: Failed to import classes from file /home/vsts/work/1/s/source/DSCResources/MSFT_SqlDatabaseUserRole/MSFT_SqlDatabaseUserRole.schema.mof. Error Exception calling "ImportClasses" with "3" argument(s): "Value cannot be null.""

Of course, the /source/DSCResources/MSFT_SqlDatabaseUserRole/MSFT_SqlDatabaseUserRole.schema.mof file exists only in my SqlDatabaseUserRole branch so far, not yet in the SqlServerDsc repository, so it can't be accessed by any build tools yet. Curiously, a search  of the entire repository did not turn up anywhere that "ImportClasses" is called, but I suspect that will be irrelevant after the SqlDatabaseUserRole branch gets added to the SqlServerDsc repository where it can be found.

**Comment by johlju** [comment]
@Rob-S  The CI pipeline builds and tests your working branch. The problem seems to the new schema.mof file is not in the correct encoding. GitHub thinks it is a binary file. Can you verify that the file (and all the other new files) has the encoding UTF-8 (without BOM).

**Comment by johlju** [comment]
Labeling this as on hold. Waiting for the discussion in issue https://github.com/dsccommunity/SqlServerDsc/issues/1488 to come to a conclusion.

**Comment by johlju** [comment]
Closing this since the issue was closed. If there are more comments on the issue this PR can be reopened.

**Pull request closed without merging**
