### PR TITLE
azure-pipelines.yml: issue #1466

### LINKED ISSUE #1466: Azure DevOps is removing older build images
The Windows Server Core 1803 image is being removed on March 23, 2020. This repository is using the image and must be removed or transition to another image as appropriate.

https://github.com/dsccommunity/SqlServerDsc/blob/209e6e53122d8c10feee6eca098afcc26153f7b4/azure-pipelines.yml#L50

https://github.com/dsccommunity/SqlServerDsc/blob/209e6e53122d8c10feee6eca098afcc26153f7b4/azure-pipelines.yml#L78

### PR DESCRIPTION
**Pull request by dwilkie1**
#### Pull Request (PR) description
 - Changed hosted agent to newer YAML VM Image Label
#### This Pull Request (PR) fixes the following issues
-Fix #1466 

#### Task list
- [X] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1467)

### CODE REVIEW

**Comment by johlju** [comment]
Seems there a low disk space on C:\on that image. Integration tests fail with
```
Exit message:                  Insufficient space available in directory C:\Program Files\Microsoft SQL 
2020-01-29T22:45:29.1096477Z Server\.  0MB is required for this feature, and 699MB is required for all features on this volume.  451MB is available.
```

Is there another disk available on the image you think? Or maybe we need to change the build image?

**Comment by dwilkie1** [comment]
> 
> 
> Seems there a low disk space on C:\on that image. Integration tests fail with
> 
> ```
> Exit message:                  Insufficient space available in directory C:\Program Files\Microsoft SQL 
> 2020-01-29T22:45:29.1096477Z Server\.  0MB is required for this feature, and 699MB is required for all features on this volume.  451MB is available.
> ```
> 
> Is there another disk available on the image you think? Or maybe we need to change the build image?

Per [this link](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#use-a-microsoft-hosted-agent) we get the following options: "windows-latest", "windows-2019" or "vs2017-win2016".
I went and got the disk info on all three:
image
image
image

For comparison, here's the current image:
image

**Comment by johlju** [comment]
Hmm. strange. According to that it should be enough disk space. 🤔 Let me kick off the tests again, see if it was temporary. 🤔

**Comment by dwilkie1** [comment]
@johlju looks like the same issue.

**Comment by johlju** [comment]
That seems very strange. Can we check how the diskspace is changing for each install in the integration test for SqlSetup? 🤔 
We could change install drive for the setup that is failing.

**Comment by dwilkie1** [comment]
I'm struggling with how to insert that into the integration test script. Can you give me a hint?

**Comment by johlju** [comment]
Absolutely. But need to work on a other stuff and must be away this weekend, but will look into this to help you as soon as I can. I have this on the todo-list. 🙂

**Comment by johlju** [comment]
@dwilkie1 Sorry I haven't been able to get to it until now. I tried to push a new branch with these changes, and it seemed to just work. I wonder if there was issues with Azure Devops when you tried last time. 🤔 

I am making other changes as well to the pipeline so I will send in a new PR that will close this one. We will see if I get the same problems when sending in a PR.

Thank you for your work on this!

**Comment by dwilkie1** [comment]
Weird well I'm glad it works now. I just used the module to deploy a couple of servers. So thank you for all your work on it!

________________________________

**Comment by johlju** [comment]
I'm glad the resources are coming to use! Please continue contributing to the resources. 😄

**Comment by johlju** [comment]
@dwilkie1 This was now fixed in PR #1480. Thank you again for your work on this! 🙇

**Pull request closed without merging**
