### PR TITLE
SqlDatabaseObjectPermission: Fixing issue with INSERT permissions

### LINKED ISSUE #2006: SqlDatabaseObjectPermission: INSERT permission never shows as InDesiredState when other permissions are on the table
### Problem description

When you are only granting INSERT permissions on a table, if INSERT is the only permission on the table, everything works as expected.  However, when there are permissions on the table other than INSERT (such as SELECT/GRANT/UPDATE), the testing of the resource will always show `InDesiredState = False`

Here is a screenshot showing with just INSERT it works as expected:
image

Here is a screenshot showing that even though both the DELETE and INSERT permissions have been set, it's stating that the permissions are not in a desired state:
image

----------------

I believe it has something to do with [this line](https://github.com/dsccommunity/SqlServerDsc/blob/main/source/DSCResources/DSC_SqlDatabaseObjectPermission/DSC_SqlDatabaseObjectPermission.psm1#L153) in the code.
`if ($true -in $currentObjectPermissions.PermissionType.$currentPermissionProperty)`

If I test that code outside of this module, we see that the `if ($true -in $currentObjectPermissions.PermissionType.$currentPermissionProperty)` block doesn't actually work with INSERT
image

Pulling the `if` block test out by itself, we get:
image

And looking at just `CurrentObjectPermissions.PermissionType.Insert` we get the following:
image

### Verbose logs

```text
PS C:\tmp> $grantInsert = New-CimInstance -ClientOnly -ClassName 'DSC_DatabaseObjectPermission' -Property @{'state' = 'Grant'; 'permission' = 'INSERT'}
$grantDelete = New-CimInstance -ClientOnly -ClassName 'DSC_DatabaseObjectPermission' -Property @{'state' = 'Grant'; 'permission' = 'DELETE'}
$InvokeParams = @{
    Name = 'SqlDatabaseObjectPermission';
    Method = 'Test';
    Property = @{
        instancename = 'MSSQLSERVER';
        objecttype = 'Table';
        databasename = 'TestDB';
        name = 'CONTOSO\marktest';
        objectname = 'TestTable';
        schemaname = 'dbo';
        permission = [CimInstance[]]@($grantInsert, $grantDelete)
       };
    ModuleName = @{
        ModuleName = 'SQLServerDsc';
        RequiredVersion = '16.5.0'
    }
}
Invoke-DscResource @InvokeParams -Verbose -Debug
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = ResourceTest,'className' = MSFT_DSCLocalConfigurationManag
er,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer SQL01 with user sid S-1-5-21-2749032974-3131961438-382479902-500.
VERBOSE: [SQL01]: LCM:  [ Start  Test     ]  [[SqlDatabaseObjectPermission]DirectResourceAccess]
VERBOSE: [SQL01]:                            [[SqlDatabaseObjectPermission]DirectResourceAccess] Determining the current state of the permissions f
or the database object 'dbo.TestTable' of type 'Table' in the database 'TestDB' for the instance 'MSSQLSERVER' on the server 'SQL01'. (SDOP0002)
VERBOSE: [SQL01]:                            [[SqlDatabaseObjectPermission]DirectResourceAccess] Getting the current state of the permissions for t
he database object 'dbo.TestTable' of type 'Table' in the database 'TestDB' for the instance 'MSSQLSERVER' on the server 'SQL01'. (SDOP0001)
DEBUG: [SQL01]:                            [[SqlDatabaseObjectPermission]DirectResourceAccess] "Sort-Object" - "CalculatedVersion" cannot be found 
in "InputObject".
VERBOSE: [SQL01]:                            [[SqlDatabaseObjectPermission]DirectResourceAccess] Connecting as current user 'NT AUTHORITY\SYSTEM' u
sing integrated security. (SQLCOMMON0054)
VERBOSE: [SQL01]:                            [[SqlDatabaseObjectPermission]DirectResourceAccess] Connected to SQL instance 'SQL01'. (SQLCOMMON0018)
DEBUG: [SQL01]:                            [[SqlDatabaseObjectPermission]DirectResourceAccess] Evaluating the state of the property 'Permission'. (
DRC0038)
DEBUG: [SQL01]:                            [[SqlDatabaseObjectPermission]DirectResourceAccess] Testing CIM instance 'DSC_DatabaseObjectPermission' 
with the key properties 'Permission="INSERT";State="Grant"'. (DRC0030)
DEBUG: [SQL01]:                            [[SqlDatabaseObjectPermission]DirectResourceAccess] String value does not match. Current value is 'Absen
t', but expected the value 'Present'. (DRC0036)
DEBUG: [SQL01]:                            [[SqlDatabaseObjectPermission]DirectResourceAccess] Testing CIM instance 'DSC_DatabaseObjectPermission' 
with the key properties 'Permission="DELETE";State="Grant"'. (DRC0030)
VERBOSE: [SQL01]:                            [[SqlDatabaseObjectPermission]DirectResourceAccess] The permissions for the database object 'dbo.TestT
able' is not in desired state. (SDOP0003)
VERBOSE: [SQL01]: LCM:  [ End    Test     ]  [[SqlDatabaseObjectPermission]DirectResourceAccess] False in 0.1280 seconds.
VERBOSE: [SQL01]: LCM:  [ End    Set      ]    in  0.2110 seconds.
VERBOSE: Operation 'Invoke CimMethod' complete.

InDesiredState 
-------------- 
False          
VERBOSE: Time taken for configuration job to complete is 0.382 seconds



PS C:\tmp>
```

### DSC configuration

```powershell
$grantInsert = New-CimInstance -ClientOnly -ClassName 'DSC_DatabaseObjectPermission' -Property @{'state' = 'Grant'; 'permission' = 'INSERT'}
$grantDelete = New-CimInstance -ClientOnly -ClassName 'DSC_DatabaseObjectPermission' -Property @{'state' = 'Grant'; 'permission' = 'DELETE'}
$InvokeParams = @{
    Name = 'SqlDatabaseObjectPermission';
    Property = @{
        instancename = 'MSSQLSERVER';
        objecttype = 'Table';
        databasename = 'TestDB';
        name = 'CONTOSO\marktest';
        objectname = 'TestTable';
        schemaname = 'dbo';
        permission = [CimInstance[]]@($grantInsert, $grantDelete)
       };
    ModuleName = @{
        ModuleName = 'SQLServerDsc';
        RequiredVersion = '16.5.0'
    }
}
Invoke-DscResource -Method Set @InvokeParams -Verbose -Debug
Invoke-DscResource -Method Test @InvokeParams -Verbose -Debug
```

### Suggested solution

My proposed solution is this:

If we wrap the `if ($true -in $currentObjectPermissions.PermissionType.$currentPermissionProperty)` block in it's own foreach loop, then it seems to work.

image

This is because when you have multiple permissions, the `$currentObjectPermissions` is an array and has the `Insert` as an `IList` method. 
image

But if you look at an individual item in the array, then the `Insert` is actually a property as expected
image

### SQL Server edition and version

```text
Microsoft SQL Server 2019 (RTM-GDR) (KB5029377) - 15.0.2104.1 (X64)   Aug 16 2023 00:09:21   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2019 Standard Evaluation 10.0 <X64> (Build 17763: ) (Hypervisor)
```

### SQL Server PowerShell modules

```text
Name  Version Path                                                                                     
----  ------- ----                                                                                     
SQLPS 15.0    C:\Program Files (x86)\Microsoft SQL Server\150\Tools\PowerShell\Modules\SQLPS\SQLPS.psd1
```

### Operating system

```text
OsName               : Microsoft Windows Server 2019 Standard Evaluation
OsOperatingSystemSKU : 79
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
```

### PowerShell version

```text
Name                           Value                                                                                                                                                           
----                           -----                                                                                                                                                           
PSVersion                      5.1.17763.5328                                                                                                                                                  
PSEdition                      Desktop                                                                                                                                                         
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                         
BuildVersion                   10.0.17763.5328                                                                                                                                                 
CLRVersion                     4.0.30319.42000                                                                                                                                                 
WSManStackVersion              3.0                                                                                                                                                             
PSRemotingProtocolVersion      2.3                                                                                                                                                             
SerializationVersion           1.1.0.1
```

### SqlServerDsc version

```text
Name         Version Path                                                                            
----         ------- ----                                                                            
SqlServerDsc 16.5.0  C:\Program Files\WindowsPowerShell\Modules\SqlServerDsc\16.5.0\SqlServerDsc.psd1
```

### PR DESCRIPTION
**Pull request by markaugust**
#### This Pull Request (PR) fixes the following issues
Adding a `foreach` loop when checking object permissions to avoid issues with INSERT permissions
- Fixes #2006 

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation updated in the resource's README.md.
- [ ] Resource parameter descriptions updated in schema.mof.
- [ ] Comment-based help updated, including parameter descriptions.
- [ ] Localization strings updated.
- [ ] Examples updated.
- [x] Unit tests updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Code changes adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2007)

### CODE REVIEW

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2007)* status: all files reviewed, 3 unresolved discussions (waiting on @markaugust)

___
*[`tests/Unit/DSC_SqlDatabaseObjectPermission.Tests.ps1` line 160 at r2](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2007#-Nx1x4lGCZyrf12ht0aV:-Nx1x4lGCZyrf12ht0aW:b-je0l3f) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/baea46976576ced805a29ee57d9bc428ecc8ac8e/tests/Unit/DSC_SqlDatabaseObjectPermission.Tests.ps1#L160)):*
> ```PowerShell
>             }
> 
>             Mock -CommandName Get-DatabaseObject -MockWith {
> ```

This mock should be updated to mimic the types that is returned when `INSERT` is used. Looks like `IList` in the issue? Then this test should fail without the suggested change, and tests should pass with the suggested change.
Do you have time to look into a changing the mock?

**Comment by markaugust** [comment]
@johlju I'm not familiar enough with Mocks and Unit test to know exactly what needs to be done here.  Looking at the code block, I made some changes to the unit test, but let me know if that's not what you were meaning.

**Comment by johlju** [comment]
I will review this PR as soon as I have time. Will look over the changes to the test you made. Good work!

**Comment by johlju** [comment]
Unit tests looks okay, it correctly fails without the proposed change. I push a change to the integration test to try to mimic the scenario in the issue.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2007#-:-NxfkNk2-NjjSbm4j60n:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @markaugust)

**Comment by johlju** [comment]
@markaugust great work on this!

**Comment by markaugust** [comment]
Thank you @johlju .  Out of curiosity, is there a timeline on when those fixes will get moved into a full release branch, rather than just in a preview branch?

**Comment by johlju** [comment]
Usually when we (community) feel there should be a new full release. I pushed a release tag now, so should release if pipeline don't fail 😊

**Pull request merged**
