### PR TITLE
Bump dbatools to v2.0.1

### PR DESCRIPTION
**Pull request by johlju**
#### Pull Request (PR) description
- SqlServerDsc
  - Bumped dbatools to v2.0.1 for the integration tests.

#### This Pull Request (PR) fixes the following issues
None. 

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation updated in the resource's README.md.
- [ ] Resource parameter descriptions updated in schema.mof.
- [ ] Comment-based help updated, including parameter descriptions.
- [ ] Localization strings updated.
- [ ] Examples updated.
- [ ] Unit tests updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Integration tests updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Code changes adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1926)

### CODE REVIEW

**Comment by johlju** [comment]
@potatoqualitee it looks like dbatools does not pin the dbatools.library correctly. I see that the dbatools.library version differ between jobs. PR 1915 uses the preview7 version and we can see that it downloads the same dbatools.library version as 2.0.0 GA. Looking at the build for the full release of SqlServerDsc the other week it passed since it used a different version of dbatools.library.

Passed | SqlServerDsc build | dbatools | using dbatools.library | CI Job 
--- | --- | --- | --- | ---
✔️ | 16.3.0 | 2.0.0-preview7 | 2023.4.18 | [16.3.0](https://dev.azure.com/dsccommunity/SqlServerDsc/_build/results?buildId=7893&view=logs&j=de5b7e59-7132-58b4-2e99-b931f815af9f&t=452b3d13-4da3-56c6-fba5-56ec18d41fc7&l=1497)
❌ | PR 1915 | 2.0.0-preview7 | 2023.4.27 | [16.4.0-PR1915.29](https://dev.azure.com/dsccommunity/SqlServerDsc/_build/results?buildId=7897&view=logs&j=617ae928-ca63-503f-e885-1aa5bed2e4f4&t=2b861645-5dd0-5cb3-4057-f553356fbcd9&l=1027)
❌ | PR 1926 | 2.0.0 | 2023.4.27 | [16.4.0-PR1926.5](https://dev.azure.com/dsccommunity/SqlServerDsc/_build/results?buildId=7908&view=logs&j=0fdaecef-867f-5ff1-72d1-514fee5aaf9a&t=7149119a-ec61-538b-79e8-700958fdef5e&l=1009)

The build for this PR was run on both Win 2019 and Win 2022 and both faild with the `System.Runtime` error.

**Comment by potatoqualitee** [comment]
What on earth? I can't figure this out. Can you give me  $PSVersionTable on that PS Console?

**Comment by johlju** [comment]
Here you go:
image

**Comment by potatoqualitee** [comment]
okay this give me a good amount of info. ill have to test the other library but this one seems to require a slightly higher version .net than is available. which sounds crazay bc as far as I know, we require a version from 2018. you're on 4.0 and we require 4.x. let me do some digging and at the very least, we'll throw a useful error message.

**Comment by potatoqualitee** [comment]
2022! what! okay gimme some time and i'll get this addressed but i think it's incompatible .net versions.

**Comment by johlju** [comment]
Thank you. Let me know if I should try to install another .net version in the pipeline. 🙂

**Comment by potatoqualitee** [comment]
But it worked the other day! I'll figure this out again 😅

**Comment by potatoqualitee** [comment]
sweet, i can repro 👍🏼  ill figure this out, fix and release then let you know

**Comment by potatoqualitee** [comment]
Got it. I had to revert to some other version of the DLL 🤷🏼  I also added a test to ensure the DLLs load.

Do you remember that script you shared in a comment that did a quick test? I'd like to add it to our test suite to ensure your tests always pass.

**Comment by potatoqualitee** [comment]
With that said, dbatools 2.0.1 should work for you 👍🏼

**Comment by johlju** [comment]
> Do you remember that script you shared in a comment that did a quick test? I'd like to add it to our test suite to ensure your tests always pass.

You mean the repro here: https://github.com/dsccommunity/SqlServerDsc/pull/1904#issuecomment-1510180744
I think this script will be enough to test it and check that `$analysisServicesObject` is correct type:

```powershell
$env:SMODefaultModuleName = 'dbatools'
import-module -Name 'dbatools'
$analysisServicesObject = New-Object -TypeName 'Microsoft.AnalysisServices.Server'
```

**Comment by johlju** [comment]
> With that said, dbatools 2.0.1 should work for you

Thank you! Will bump to that version. 🙇‍♂️

**Comment by potatoqualitee** [comment]
it was the "Script"command that helped ensure SqlServerDsc could uhh make a mof? Quite a few lines.

**Comment by johlju** [comment]
The first issue was that when importing the module inside the LCM’s PowerShell process it failed. If you want to run a DSC resource with LCM we could make an easier integration test using `Invoke-DscResource`. I can look into it tomorrow and see I can simplify it a bit.

**Review by johlju — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1926#-:-NUlaQ1a1HosidxweChm:bnfp4nl)* status: 2 of 4 files reviewed, all discussions resolved

**Comment by potatoqualitee** [comment]
🥳

**Comment by johlju** [comment]
@potatoqualitee There are two options to run integration tests. All require Windows PowerShell and a SQL Server instance available to connect to to create a SQL login. 

For both options this should be run (change paths as required):

```powershell
# Remove any installed SqlServer och SQLPS modules from the build worker (host that runs the integration tests).
# See here for a function that could be inspiration (or re-use): https://github.com/dsccommunity/SqlServerDsc/blob/7d58bf5dfc4d951778ed5f3fe19821ddfb309ca8/tests/TestHelpers/CommonTestHelper.psm1#L442-L517

Set-ExecutionPolicy RemoteSigned -Force
winrm quickconfig -quiet
Install-Module SqlServerDsc -RequiredVersion 16.3.1 -Scope AllUsers -Force
Install-Module PSDscResources -RequiredVersion '2.12.0.0' -Scope AllUsers -Force
Copy-Item -Path './dbatools' -Destination 'C:\Program Files\WindowsPowerShell\Modules' -Recurse -Force
Copy-Item -Path './dbatools.library' -Destination 'C:\Program Files\WindowsPowerShell\Modules' -Recurse -Force
```

### Option #1

If you make sure the machine environment variable is set prior to LCM is run this might work, so the LCM's PowerShell process sees the environment variable, this might be sufficient (but if it requires a restart then this option is not gonna work). If it works it should _NOT_ output a verbose statement saying `No preferred PowerShell module was found`. Change values as required.

```powershell
$loginPassword = [PSCredential]::new(
    'NotUsed',
    ('MyPassword' | ConvertTo-SecureString -AsPlainText -Force)
)

Invoke-DscResource -ModuleName 'SqlServerDsc' -Name 'SqlLogin' -Method 'Get' -Property @{
    Ensure                         = 'Present'
    Name                           = 'TestDSCUser'
    LoginType                      = 'SqlLogin'
    ServerName                     = 'TestServer.company.local'
    InstanceName                   = 'DSC'
    LoginCredential                = $loginPassword
    LoginMustChangePassword        = $false
    LoginPasswordExpirationEnabled = $true
    LoginPasswordPolicyEnforced    = $true

    # If SYSTEM is not allowed to connect to the SQl instance, set this to credentials allowed to connect to SQL instance.
    #PsDscRunAsCredential           = $SqlAdministratorCredential 
} -Verbose
```

### Option #2

If above `Invoke-DscResource` does not work (if it can't see the environment variable) then this is required. The below compiles a MOF configuration and puses it to the local node, then make the node forget it had a configuration pushed. Change values as required.

```powershell
$loginPassword = [PSCredential]::new(
    'NotUsed',
    ('MyPassword' | ConvertTo-SecureString -AsPlainText -Force)
)


Configuration Example
{
    Import-DscResource -ModuleName PSDscResources
    Import-DscResource -ModuleName SqlServerDsc

    node localhost
    {
        Environment 'SetSMODefaultModuleName'
        {
            Name = 'SMODefaultModuleName'
            Value = 'dbatools'
            Ensure = 'Present'
            Path = $false
            Target = @('Process', 'Machine')
        }

        SqlLogin 'CreateSqlLogin'
        {
            Ensure                         = 'Present'
            Name                           = 'TestDSCUser'
            LoginType                      = 'SqlLogin'
            ServerName                     = 'TestServer.company.local'
            InstanceName                   = 'DSC'
            LoginCredential                = $loginPassword
            LoginMustChangePassword        = $false
            LoginPasswordExpirationEnabled = $true
            LoginPasswordPolicyEnforced    = $true

            # If SYSTEM is not allowed to connect to the SQl instance, set this to credentials allowed to connect to SQL instance.
            #PsDscRunAsCredential           = $SqlAdministratorCredential
        }
    }
}

$configurationData = @{
    AllNodes    = , @{
        NodeName        = 'localhost'
        PSDSCAllowPlainTextPassword = $true
        PSDscAllowDomainUser = $true
    }
}

Example -OutputPath c:\DSC -ConfigurationData $configurationData

Start-DscConfiguration -Wait -Force -Path C:\DSC -ComputerName localhost -Verbose

Remove-DscConfigurationDocument -Stage Current,Pending,Previous -Force -Verbose
```

**Pull request merged**
