### PR TITLE
Assert-ElevatedUser: Function moved to DscResource.Common Module

### LINKED ISSUE #1797: Assert-ElevatedUser: Move to DscResource.Common as a public command
We should look at moving this to DscResource.Common (as a public command).

### PR DESCRIPTION
**Pull request by hollanjs**
#### Pull Request (PR) description
Moved `Assert-ElevatedUser` from a private function in SqlServerDsc to a public function in DscResource.Common
Related Issue adding function to DscResource.Common: [Issue #82](https://github.com/dsccommunity/DscResource.Common/issues/82)

#### This Pull Request (PR) fixes the following issues
- Fixes #1797

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation updated in the resource's README.md.
- [ ] Resource parameter descriptions updated in schema.mof.
- [ ] Comment-based help updated, including parameter descriptions.
- [x] Localization strings updated.
- [ ] Examples updated.
- [ x Unit tests updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Code changes adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1815)

### CODE REVIEW

**Comment by hollanjs** [comment]
@johlju - My PR for issue #1797. Let me know if it requires any additional updates or changes.

**Comment by johlju** [comment]
I'm trying to figure out why the build fails. It has nothing to do with this PR. Probably an issue on the build worker as Azure Pipelines shifted linux version.

**Comment by johlju** [comment]
@hollanjs great work on this. Much appreciated to gotten this command moved! 🙇

**Pull request merged**
