### PR TITLE
SqlDatabaseUser: Execute Set-TargetResource when database IsUpdateable is $true

### LINKED ISSUE #1748: SqlDatabaseUser: Tries to create a user on a read-only secondary
### Problem description

When a database is a read-only secondary in an Availability Group, the resource sees the database user does not exist and tries to add the user.

### Verbose logs

```text
{"time": "2022-06-04T16:02:41.353+00:00", "type": "verbose", "message": "[SqlServer01]: LCM:  [ Start  Resource ]  [[SqlDatabaseUser]OperationsManager-Contoso\\UserToCreate::[SqlServerStandaloneInstance]SqlServerStandaloneInstance]  "},
  {"time": "2022-06-04T16:02:41.353+00:00", "type": "verbose", "message": "[SqlServer01]: LCM:  [ Start  Test     ]  [[SqlDatabaseUser]OperationsManager-Contoso\\UserToCreate::[SqlServerStandaloneInstance]SqlServerStandaloneInstance]  "},
  {"time": "2022-06-04T16:02:41.468+00:00", "type": "verbose", "message": "[SqlServer01]:                            [[SqlDatabaseUser]OperationsManager-Contoso\\UserToCreate::[SqlServerStandaloneInstance]SqlServerStandaloneInstance] Determining if the database user 'Contoso\\UserToCreate$' in the database 'OperationsManager' is in the desired state. (SDU0003)"},
  {"time": "2022-06-04T16:02:41.468+00:00", "type": "verbose", "message": "[SqlServer01]:                            [[SqlDatabaseUser]OperationsManager-Contoso\\UserToCreate::[SqlServerStandaloneInstance]SqlServerStandaloneInstance] Found PowerShell module SQLPS already imported in the session. (SQLCOMMON0026)"},
  {"time": "2022-06-04T16:02:41.468+00:00", "type": "verbose", "message": "[SqlServer01]:                            [[SqlDatabaseUser]OperationsManager-Contoso\\UserToCreate::[SqlServerStandaloneInstance]SqlServerStandaloneInstance] Connecting as current user 'Contoso\\DscServiceAccount' using integrated security. (SQLCOMMON0054)"},
  {"time": "2022-06-04T16:02:41.468+00:00", "type": "verbose", "message": "[SqlServer01]:                            [[SqlDatabaseUser]OperationsManager-Contoso\\UserToCreate::[SqlServerStandaloneInstance]SqlServerStandaloneInstance] Connected to SQL instance 'SqlServer01'. (SQLCOMMON0018)"},
  {"time": "2022-06-04T16:02:41.468+00:00", "type": "verbose", "message": "[SqlServer01]:                            [[SqlDatabaseUser]OperationsManager-Contoso\\UserToCreate::[SqlServerStandaloneInstance]SqlServerStandaloneInstance] Retrieving information about the database user 'Contoso\\UserToCreate$' from the database 'OperationsManager'. (SDU0001)"},
  {"time": "2022-06-04T16:02:41.468+00:00", "type": "verbose", "message": "[SqlServer01]:                            [[SqlDatabaseUser]OperationsManager-Contoso\\UserToCreate::[SqlServerStandaloneInstance]SqlServerStandaloneInstance] The database user 'Contoso\\UserToCreate$' does not exist in the database 'OperationsManager'. (SDU0005)"},
  {"time": "2022-06-04T16:02:41.468+00:00", "type": "verbose", "message": "[SqlServer01]:                            [[SqlDatabaseUser]OperationsManager-Contoso\\UserToCreate::[SqlServerStandaloneInstance]SqlServerStandaloneInstance] The database user is not in desired state. (SDU0007)"},
  {"time": "2022-06-04T16:02:41.478+00:00", "type": "verbose", "message": "[SqlServer01]: LCM:  [ End    Test     ]  [[SqlDatabaseUser]OperationsManager-Contoso\\UserToCreate::[SqlServerStandaloneInstance]SqlServerStandaloneInstance]  in 0.1250 seconds."},
  {"time": "2022-06-04T16:02:41.478+00:00", "type": "verbose", "message": "[SqlServer01]: LCM:  [ Start  Set      ]  [[SqlDatabaseUser]OperationsManager-Contoso\\UserToCreate::[SqlServerStandaloneInstance]SqlServerStandaloneInstance]  "},
  {"time": "2022-06-04T16:02:41.733+00:00", "type": "verbose", "message": "[SqlServer01]:                            [[SqlDatabaseUser]OperationsManager-Contoso\\UserToCreate::[SqlServerStandaloneInstance]SqlServerStandaloneInstance] Setting the database user 'Contoso\\UserToCreate$' in the database 'OperationsManager' to the desired state. (SDU0019)"},
  {"time": "2022-06-04T16:02:41.733+00:00", "type": "verbose", "message": "[SqlServer01]:                            [[SqlDatabaseUser]OperationsManager-Contoso\\UserToCreate::[SqlServerStandaloneInstance]SqlServerStandaloneInstance] Found PowerShell module SQLPS already imported in the session. (SQLCOMMON0026)"},
  {"time": "2022-06-04T16:02:41.733+00:00", "type": "verbose", "message": "[SqlServer01]:                            [[SqlDatabaseUser]OperationsManager-Contoso\\UserToCreate::[SqlServerStandaloneInstance]SqlServerStandaloneInstance] Connecting as current user 'Contoso\\DscServiceAccount' using integrated security. (SQLCOMMON0054)"},
  {"time": "2022-06-04T16:02:41.733+00:00", "type": "verbose", "message": "[SqlServer01]:                            [[SqlDatabaseUser]OperationsManager-Contoso\\UserToCreate::[SqlServerStandaloneInstance]SqlServerStandaloneInstance] Connected to SQL instance 'SqlServer01'. (SQLCOMMON0018)"},
  {"time": "2022-06-04T16:02:41.733+00:00", "type": "verbose", "message": "[SqlServer01]:                            [[SqlDatabaseUser]OperationsManager-Contoso\\UserToCreate::[SqlServerStandaloneInstance]SqlServerStandaloneInstance] Retrieving information about the database user 'Contoso\\UserToCreate$' from the database 'OperationsManager'. (SDU0001)"},
  {"time": "2022-06-04T16:02:41.733+00:00", "type": "verbose", "message": "[SqlServer01]:                            [[SqlDatabaseUser]OperationsManager-Contoso\\UserToCreate::[SqlServerStandaloneInstance]SqlServerStandaloneInstance] The database user 'Contoso\\UserToCreate$' does not exist in the database 'OperationsManager'. (SDU0005)"},
  {"time": "2022-06-04T16:02:41.733+00:00", "type": "verbose", "message": "[SqlServer01]:                            [[SqlDatabaseUser]OperationsManager-Contoso\\UserToCreate::[SqlServerStandaloneInstance]SqlServerStandaloneInstance] Creating the database user 'Contoso\\UserToCreate$' in the database 'OperationsManager' with the user type 'Login'. (SDU0012)"},
  {"time": "2022-06-04T16:02:41.733+00:00", "type": "verbose", "message": "[SqlServer01]:                            [[SqlDatabaseUser]OperationsManager-Contoso\\UserToCreate::[SqlServerStandaloneInstance]SqlServerStandaloneInstance] Found PowerShell module SQLPS already imported in the session. (SQLCOMMON0026)"},
  {"time": "2022-06-04T16:02:41.733+00:00", "type": "verbose", "message": "[SqlServer01]:                            [[SqlDatabaseUser]OperationsManager-Contoso\\UserToCreate::[SqlServerStandaloneInstance]SqlServerStandaloneInstance] Connecting as current user 'Contoso\\DscServiceAccount' using integrated security. (SQLCOMMON0054)"},
  {"time": "2022-06-04T16:02:41.733+00:00", "type": "verbose", "message": "[SqlServer01]:                            [[SqlDatabaseUser]OperationsManager-Contoso\\UserToCreate::[SqlServerStandaloneInstance]SqlServerStandaloneInstance] Connected to SQL instance 'SqlServer01'. (SQLCOMMON0018)"},
  {"time": "2022-06-04T16:02:41.733+00:00", "type": "verbose", "message": "[SqlServer01]:                            [[SqlDatabaseUser]OperationsManager-Contoso\\UserToCreate::[SqlServerStandaloneInstance]SqlServerStandaloneInstance] Found PowerShell module SQLPS already imported in the session. (SQLCOMMON0026)"},
  {"time": "2022-06-04T16:02:41.733+00:00", "type": "verbose", "message": "[SqlServer01]:                            [[SqlDatabaseUser]OperationsManager-Contoso\\UserToCreate::[SqlServerStandaloneInstance]SqlServerStandaloneInstance] Connecting as current user 'Contoso\\DscServiceAccount' using integrated security. (SQLCOMMON0054)"},
  {"time": "2022-06-04T16:02:41.733+00:00", "type": "verbose", "message": "[SqlServer01]:                            [[SqlDatabaseUser]OperationsManager-Contoso\\UserToCreate::[SqlServerStandaloneInstance]SqlServerStandaloneInstance] Connected to SQL instance 'SqlServer01'. (SQLCOMMON0018)"},
  {"time": "2022-06-04T16:02:41.733+00:00", "type": "verbose", "message": "[SqlServer01]:                            [[SqlDatabaseUser]OperationsManager-Contoso\\UserToCreate::[SqlServerStandaloneInstance]SqlServerStandaloneInstance] Executing the query `CREATE USER [Contoso\\UserToCreate$] FOR LOGIN [Contoso\\UserToCreate$];`. (SQLCOMMON0058)"},
  {"time": "2022-06-04T16:02:41.803+00:00", "type": "verbose", "message": "[SqlServer01]: LCM:  [ End    Set      ]  [[SqlDatabaseUser]OperationsManager-Contoso\\UserToCreate::[SqlServerStandaloneInstance]SqlServerStandaloneInstance]  in 0.3250 seconds."},
  {"time": "2022-06-04T16:02:41.803+00:00", "type": "error", "message": "PowerShell DSC resource DSC_SqlDatabaseUser  failed to execute Set-TargetResource functionality with error message: System.InvalidOperationException: Failed creating the database user 'Contoso\\UserToCreate$' in the database 'OperationsManager' with the user type 'Login'. (SDU0013) ---> System.Exception: System.InvalidOperationException: Executing non-query failed on database 'OperationsManager'. (SQLCOMMON0046) ---> System.Management.Automation.MethodInvocationException: Exception calling \"ExecuteNonQuery\" with \"1\" argument(s): \"ExecuteNonQuery failed for Database 'OperationsManager'. \" ---> Microsoft.SqlServer.Management.Smo.FailedOperationException: ExecuteNonQuery failed for Database 'OperationsManager'.  ---> Microsoft.SqlServer.Management.Common.ExecutionFailureException: An exception occurred while executing a Transact-SQL statement or batch. ---> System.Data.SqlClient.SqlException: The target database ('OperationsManager') is in an availability group and is currently accessible for connections when the application intent is set to read only. For more information about application intent, see SQL Server Books Online.\r\n   at Microsoft.SqlServer.Management.Common.ConnectionManager.ExecuteTSql(ExecuteTSqlAction action, Object execObject, DataSet fillDataSet, Boolean catchException)\r\n   at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteNonQuery(String sqlCommand, ExecutionTypes executionType, Boolean retry)\r\n   --- End of inner exception stack trace ---\r\n   at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteNonQuery(String sqlCommand, ExecutionTypes executionType, Boolean retry)\r\n   at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteNonQuery(StringCollection sqlCommands, ExecutionTypes executionType, Boolean retry)\r\n   at Microsoft.SqlServer.Management.Smo.ExecutionManager.ExecuteNonQuery(StringCollection queries, ExecutionTypes executionType)\r\n   at Microsoft.SqlServer.Management.Smo.Database.ExecuteNonQuery(StringCollection sqlCommands, ExecutionTypes executionType)\r\n   --- End of inner exception stack trace ---\r\n   at Microsoft.SqlServer.Management.Smo.Database.ExecuteNonQuery(StringCollection sqlCommands, ExecutionTypes executionType)\r\n   at CallSite.Target(Closure , CallSite , Object , String )\r\n   --- End of inner exception stack trace ---\r\n   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)\r\n   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)\r\n   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)\r\n   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)\r\n   --- End of inner exception stack trace ---\r\n   --- End of inner exception stack trace --- "},
```

### DSC configuration

```powershell
SqlDatabaseUser $sqlDatabaseUserResourceName
{
    DatabaseName = $databaseName
    DependsOn = '[SqlSetup]InstallDefaultInstance'
    Ensure = 'Present'
    InstanceName = $SqlInstanceName
    LoginName = $userName
    Name = $userName
    PsDscRunAsCredential = $DscServiceAccountCredential
    UserType = 'Login'
}
```

### Suggested solution

`Get-TargetResource` should retrieve the `IsUpdateable` property from the `Microsoft.SqlServer.Management.Smo.Database` object. `Test-TargetResource` should return `$false` only if the user is not in the desired state and the `IsUpdateable` property is `$true`.

### SQL Server edition and version

```text
Microsoft SQL Server 2019 (RTM-CU16) (KB5011644) - 15.0.4223.1 (X64) 
	Apr 11 2022 16:24:07 
	Copyright (C) 2019 Microsoft Corporation
	Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2019 Datacenter 10.0 <X64> (Build 17763: ) (Hypervisor)
```

### SQL Server PowerShell modules

```text
Name  Version Path
----  ------- ----
SQLPS 15.0    E:\Program Files (x86)\Microsoft SQL Server\150\Tools\PowerShell\Modules\SQLPS\SQLPS.psd1
```

### Operating system

```text
OsName               : Microsoft Windows Server 2019 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
```

### PowerShell version

```text
Name                           Value                                                                                                                                                
----                           -----                                                                                                                                                
PSRemotingProtocolVersion      2.3                                                                                                                                                  
BuildVersion                   10.0.17763.2867                                                                                                                                      
PSVersion                      5.1.17763.2867                                                                                                                                       
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                              
PSEdition                      Desktop                                                                                                                                              
CLRVersion                     4.0.30319.42000                                                                                                                                      
WSManStackVersion              3.0                                                                                                                                                  
SerializationVersion           1.1.0.1
```

### SqlServerDsc version

```text
Name         Version Path                                                                            
----         ------- ----                                                                            
SqlServerDsc 15.2.0  C:\Program Files\WindowsPowerShell\Modules\SqlServerDsc\15.2.0\SqlServerDsc.psd1
```

### PR DESCRIPTION
**Pull request by randomnote1**
#### Pull Request (PR) description
Retrieved the `IsUpdateable` property from the database object. If `IsUpdateable` is `$false`, then `Test-TargetResource` returns `$true`

#### This Pull Request (PR) fixes the following issues
- Fixes #1748

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [x] Resource documentation updated in the resource's README.md.
- [x] Resource parameter descriptions updated in schema.mof.
- [ ] Comment-based help updated, including parameter descriptions.
- [ ] Localization strings updated.
- [ ] Examples updated.
- [x] Unit tests updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Code changes adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1749)

### CODE REVIEW

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1749#-:-N3nIyrAAl0RDkkEffLB:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @randomnote1)

**Comment by johlju** [comment]
Great work @randomnote1 !

**Comment by randomnote1** [comment]
Hey @johlju, are we still able to calculate code coverage locally? I ran `.\build.ps1` followed by `Invoke-Pester .\tests\Unit\DSC_SqlDatabaseUser.Tests.ps1 -CodeCoverage .\source\DSCResources\DSC_SqlDatabaseUser\DSC_SqlDatabaseUser.psm1`, but I'm getting 0% coverage.

**Comment by johlju** [comment]
We test the built module, so you need to point to the psm1 file in the output folder.

**Comment by randomnote1** [comment]
Thanks! This has changed a bit since I last contributed.

**Comment by johlju** [comment]
Once the PR to support Pester 5 is merged it will be different again since you have to pass a `New-PesterConfiguration` filled with the code coverage path to `Invoke-Pester`. 

Maybe we should simplify that by adding a `CodeCovergePath` to `build.ps1` so it possible to write `.\build.ps1 -Task test -PesterPath ‘testfile’ -CodeCoveragePath ‘code_script_file’`

**Comment by randomnote1** [comment]
That sounds like a good idea. I have to admit, I'm not tracking on any of the Pester 5 changes, so I'll understand more when I use it the first time.

**Pull request merged**
