### PR TITLE
SqlTraceFlag: Fix for #1688

### LINKED ISSUE #1688: SqlTraceFlag: Cannot bind argument to parameter 'ReferenceObject' because it is null.
#### Details of the scenario you tried and the problem that is occurring
Re-testing SqlTraceFlag with basic configuration.

Assemblies are now loaded as per resolved issue #1680 but now running into new problems 😢 .

First error thrown relates to `Test-TargetResource` where TraceFlags is compared with Actual TraceFlags: https://github.com/dsccommunity/SqlServerDsc/blob/main/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L375

Not sure why ReferenceObject would be null - I tried running sections of the code manually and it seems to generate the required object.

@Fiander @johlju you may have interest in this. Thanks

#### Verbose logs showing the problem
```
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/Desi
redStateConfiguration'.
VERBOSE: An LCM method call arrived from computer SOMENAME with user sid SOMESID.
VERBOSE: [SOMENAME]: LCM:  [ Start  Set      ]
VERBOSE: [SOMENAME]: LCM:  [ Start  Resource ]  [[SqlTraceFlag]Set_SqlTraceFlags]
VERBOSE: [SOMENAME]: LCM:  [ Start  Test     ]  [[SqlTraceFlag]Set_SqlTraceFlags]
VERBOSE: [SOMENAME]:                            [[SqlTraceFlag]Set_SqlTraceFlags] Determines the current state of the TraceFlags Compared to the desired TraceFlags 'MSSQLSERVER'.
VERBOSE: [SOMENAME]:                            [[SqlTraceFlag]Set_SqlTraceFlags] Information: PowerShell module SqlServer not found, trying to use older SQLPS module. (SQLCOMMON0024)
VERBOSE: [SOMENAME]:                            [[SqlTraceFlag]Set_SqlTraceFlags] Importing PowerShell module 'SQLPS' with version '1.0' from path 'C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Pow
erShell\Modules\SQLPS\SQLPS.psd1'. (SQLCOMMON0025)
VERBOSE: [SOMENAME]:                            [[SqlTraceFlag]Set_SqlTraceFlags] Get the current TraceFlags that are set on instance MSSQLSERVER.
Cannot bind argument to parameter 'ReferenceObject' because it is null.
    + CategoryInfo          : InvalidData: (:) [], CimException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand
    + PSComputerName        : localhost
 
VERBOSE: [SOMENAME]: LCM:  [ End    Test     ]  [[SqlTraceFlag]Set_SqlTraceFlags]  in 2.7510 seconds.
The PowerShell DSC resource '[SqlTraceFlag]Set_SqlTraceFlags' with SourceInfo 'C:\users\SOME_USERNAME\Desktop\Example.ps1::8::9::SqlTraceFlag' threw one or more non-terminating errors while running the 
Test-TargetResource functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : localhost
 
VERBOSE: [SOMENAME]: LCM:  [ End    Set      ]
The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : localhost
 
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 3.989 seconds

```
#### Suggested solution to the issue
N/A

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
Configuration Example
{

    Import-DscResource -ModuleName 'SqlServerDsc'

    node localhost
    {
        SqlTraceFlag 'Set_SqlTraceFlags'
        {
            InstanceName         = 'MSSQLSERVER'
            TraceFlags           = 3226
            RestartService       = $true
        }
    }
}

Example
```

#### SQL Server edition and version the target node is running
```
Microsoft SQL Server 2016 (SP2-CU15-GDR) (KB4583461) - 13.0.5865.1 (X64)
```

#### SQL Server PowerShell modules present on the target node
```
Name  Version Path
----  ------- ----
SQLPS 1.0     C:\Program Files (x86)\Microsoft SQL Server\130\Tools\PowerShell\Modules\SQLPS\SQLPS.psd1
```
#### The operating system the target node is running
```
OsName               : Microsoft Windows Server 2019 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

```

#### Version and build of PowerShell the target node is running
```
Name                           Value                                                                                                                                                                        
----                           -----                                                                                                                                                                        
PSVersion                      5.1.17763.1490                                                                                                                                                               
PSEdition                      Desktop                                                                                                                                                                      
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                      
BuildVersion                   10.0.17763.1490                                                                                                                                                              
CLRVersion                     4.0.30319.42000                                                                                                                                                              
WSManStackVersion              3.0                                                                                                                                                                          
PSRemotingProtocolVersion      2.3                                                                                                                                                                          
SerializationVersion           1.1.0.1                                                                                                                                                                      

```
#### Version of the DSC module that was used
```
Name         Version Path                                                                            
----         ------- ----                                                                            
SqlServerDsc 15.1.0  C:\Program Files\WindowsPowerShell\Modules\SqlServerDsc\15.1.0\SqlServerDsc.psd1
```

### PR DESCRIPTION
**Pull request by Fiander**
#### Pull Request (PR) description

Added two empty arrays so the compare object never sees a $nul 

#### This Pull Request (PR) fixes the following issues

- Fixes #1688

#### Task list

- [x ] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation updated in the resource's README.md.
- [ ] Resource parameter descriptions updated in schema.mof.
- [ ] Comment-based help updated, including parameter descriptions.
- [ ] Localization strings updated.
- [ ] Examples updated.
- [x] Unit tests updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Code changes adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1689)

### CODE REVIEW

**Review by johlju — APPROVED** [review]
> Reviewed 1 of 10 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1689)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Fiander)

**Comment by Fiander** [comment]
euh?
@johlju   why are we waiting on me?

i dont see any action to do?

**Comment by johlju** [comment]
@Fiander I was looking if I could rebase this myself. But I couldn't find a easy way :/ thought I spare you the job. 😄  Could you please rebase this PR against main. So that the CHANGELOG.md is correct, currently it proposes to remove a part of the existing CHANGELOG.

**Comment by Fiander** [comment]
oke, wil do

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1689#-:-MTHAkC_0S5Y1mCFGFzu:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by Fiander** [comment]
Damm you are quick :-) did not even have time to give you a heads up

**Comment by johlju** [comment]
Haha I was actually in Reviewable and saw it was missing a header, and when I was about to comment on it Reviewable refreshed for the new commit you pushes and the header was there 😂

**Comment by johlju** [comment]
Will probably merge tomorrow because I’m probably in bed when the finishes 😃

**Comment by Fiander** [comment]
:astonished: you sleep? I don't have time for that.

**Comment by johlju** [comment]
@Fiander haha I have noticed the mind works better after some sleep 😉

**Pull request merged**
