### PR TITLE
[#1509] SSRS 2019 initialization fix.

### LINKED ISSUE #1509: SqlRs: Reporting Services 2019 Configuration SQLRS Error
#### Details of the scenario you tried and the problem that is occurring
    Installation and Configuration of Reporting Services 2019.
    During installation (default, see code) i do not get any error.
     Configuration with SQLRS shows and error at the end, see follwing DSC log.
    In SSRS logs i am just see these errors, but after service restart/Server reboot
    the same will be disappear:
    FailedToDecryptConfigInformation: Dsn
    ERROR: Throwing 
    Microsoft.ReportingServices.Diagnostics.Utilities.ServerConfigurationErrorExcept
    ion: No DSN present in configuration file, 
    Microsoft.ReportingServices.Diagnostics.Utilities.ServerConfigurationErrorExcept
    ion: The report server has encountered a configuration error. ;
    As mentioned, after Reboot of Server i do not see any errors in SSRS logs and i 
    am not able to see any issues problems, **hence the question? why do i get the 
    errors in DSC log below??**
    **DSC LOG of SQLRS**
    VERBOSE: [sql2019tst4]:                            [[SqlRS]DefaultConfiguration]
    Operation 'Invoke CimMethod' complete.
    VERBOSE: [sql2019tst4]: LCM:  [ End    Set      ]  [[SqlRS]DefaultConfiguration]
    in 38.6310 seconds.
    PowerShell DSC resource MSFT_SqlRS  failed to execute Set-TargetResource 
    functionality with error message: Method InitializeReportServer() failed with an
    error. Error: 
    The report server has encountered a configuration error.  
    (rsServerConfigurationError) (HRESULT:-2146233088) 
        + CategoryInfo          : InvalidOperation: (:) [], CimException
        + FullyQualifiedErrorId : ProviderOperationExecutionFailure
        + PSComputerName        : localhost
     
    VERBOSE: [sql2019tst4]: LCM:  [ End    Set      ]
    The SendConfigurationApply function did not succeed.
        + CategoryInfo          : NotSpecified: 
    (root/Microsoft/...gurationManager:String) [], CimException
        + FullyQualifiedErrorId : MI RESULT 1
        + PSComputerName        : localhost
     
    VERBOSE: Operation 'Invoke CimMethod' complete.
    VERBOSE: Time taken for configuration job to complete is 40.324 seconds
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
  Configuration InstallRS
    {
    Import-DscResource -ModuleName 'SqlServerDsc'
        node localhost
        {
            SqlRSSetup 'InstallDefaultInstance'
            {
                InstanceName         = 'SSRS'
                IAcceptLicenseTerms   = 'Yes'
                SourcePath           = 'C:\sql2019\ReportingServices\
    SQLServerReportingServices.exe'
                ProductKey           = "xxxxxxxxxxxxxxxx"
            }
        }
    }
    InstallRS
    Start-DscConfiguration -Path C:\windows\system32\InstallRS -Wait -force -Verbose
    Configuration ConfigureRS
    {
    Import-DscResource -ModuleName 'SqlServerDsc'
        node localhost
        {
            SqlRS 'DefaultConfiguration'
            {
                InstanceName         = 'SSRS'
                DatabaseServerName   = 'localhost'
                DatabaseInstanceName = 'MSSQLSERVER'
            }
        }
    }
    ConfigureRS
    Start-DscConfiguration -Path C:\windows\system32\ConfigureRS -Wait -Force -
    Verbose
```

#### SQL Server edition and version the target node is running
 Microsoft SQL Server 2019 (RTM-CU4) (KB4548597) - 15.0.4033.1 (X64)   Mar 14 
    2020 16:10:35   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition: 
    Core-based Licensing (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> 
    (Build 14393: ) (Hypervisor) 

#### SQL Server PowerShell modules present on the target node
    SQLPS 15.0    C:\Program Files (x86)\Microsoft SQL Server\150\Tools\PowerShell\
    Modules\SQLPS\SQLPS.psd1

#### The operating system the target node is running
    OsName               : Microsoft Windows Server 2016 Datacenter
    OsOperatingSystemSKU : DatacenterServerEdition
    OsArchitecture       : 64-bit
    WindowsBuildLabEx    : 14393.3564.amd64fre.rs1_release.200303-1942
    OsLanguage           : en-US
    OsMuiLanguages       : {en-US}

#### Version and build of PowerShell the target node is running
 Name                           Value                                            
    ----                           -----                                            
    PSVersion                      5.1.14393.3471                                   
    PSEdition                      Desktop                                          
    PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                          
    BuildVersion                   10.0.14393.3471                                  
    CLRVersion                     4.0.30319.42000                                  
    WSManStackVersion              3.0                                              
    PSRemotingProtocolVersion      2.3                                              
    SerializationVersion           1.1.0.1        

#### Version of the DSC module that was used
    Name         Version  Path                                                      
    ----         -------  ----                                                      
    SqlServerDsc 13.2.0.0 C:\Program Files\WindowsPowerShell\Modules\SqlServerDsc\
    13.2.0.0\SqlServerDsc.psd1

### PR DESCRIPTION
**Pull request by bozho**
#### Pull Request (PR) description
`SqlRS`: SSRS 2019 initialization fix.

#### This Pull Request (PR) fixes the following issues

- Fixes #1509

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation updated in the resource's README.md.
- [ ] Resource parameter descriptions updated in schema.mof.
- [ ] Comment-based help updated, including parameter descriptions.
- [ ] Localization strings updated.
- [ ] Examples updated.
- [ ] Unit tests updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Code changes adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1698)

### CODE REVIEW

**Comment by bozho** [comment]
@johlju I've done some testing on SSRS 2016, 2017 and 2019. It seems that executing `InitializeReportServer` is not needed on SSRS 2016 and 2017 if we simply restart SSRS service (which flips the `IsInitialized` to `$true` on every SSRS version).

That means we can probably remove the code that calls it (and update relevant unit tests). If we decide to leave the code as it is now, it is unclear if there's ever a scenario where executing `InitializeReportServer` would be needed after restarting SSRS service.

Furthermore, regarding unit tests, the unit test for uninitialised SSRS will have to have two scenarios, one with `UseSSL` set to `$true` and one with `UseSSL` set to `$false`, as the number of calls to `Restart-ReportingServicesService` depends on its value.

**Comment by bozho** [comment]
Something I've noticed in my tests for SSRS 2019...

In my configuration, I have a custom DSC resource which connects to SSRS server to set some stuff up. It runs immediately after `SqlRs`. The custom resource uses a small helper function to connect to SSRS proxy URL (`.../ReportService2010.asmx?WSDL`).

The function performs a small retry loop, sending a `GET` request to the proxy URL using `[System.Net.WebRequest]`, to "prime" the server, since SSRS may return a `503` for a bit after a restart. I've noticed that SSRS 2019 pretty consistently returns `401` for a few seconds after this initialisation restart and retrying once or twice makes the `401` go away.

I was wondering if this is something we should add to `SqlRs` resource or simply document the behaviour? If we choose to implement "priming" the server after a restart, I'm not sure if there's a safe/proper way to decide which reserved URL to use...

**Comment by johlju** [comment]
@bozho sorry I haven't been available but there is a lot of stuff going on with the day job so have not as much time as I want. 

> I was wondering if this is something we should add to SqlRs

This sounds like a `WaitForSqlRs` resource? 🤔 Essentially you are waiting for the Reporting Services to start and then "warming" it up (or "prime" as you said).

> That means we can probably remove the code that calls it

We could have different paths for different versions on Reporting Services. If it needed for older SQL Reporting Services then we can keep it but not use it for newer. 🤔 

I think we need to get the integration tests working again for Reporting Services as they were disabled when moving to the new pipeline.

**Comment by bozho** [comment]
> This sounds like a WaitForSqlRs resource? 🤔 Essentially you are waiting for the Reporting Services to start and then "warming" it up (or "prime" as you said).

Maybe... Although, I think any custom resource dealing with SSRS would have to be able to handle SSRS warming up. For example, DSC might've rebooted the machine and carried on with running the configuration when it hits our custom SSRS resource... You could put the proposed `WaitForSqlRs` resource before any resources dealing with SSRS, but that seems a bit "meh" :-)

> We could have different paths for different versions on Reporting Services. If it needed for older SQL Reporting Services then we can keep it but not use it for newer.

I've tested on SQL 2016-2019 Standard. All of them were initialised when restarted immediately after executing `SetDatabaseConnection` and there was no need to execute `InitializeReportServer` (IIRC, the call always fails if SSRS is initialised). We can be a bit defensive and leave the code as it is now (it will execute `InitializeReportServer` if SSRS is not initialised after the restart).

**Comment by bozho** [comment]
Hi @johlju,

Any chance you have a look at this, help me figure out the problems above?

Thank you!

**Comment by johlju** [comment]
I will have a look. I been off for a few weeks due to vacation. But will be focusing on the SqlServerDsc for a while now. 😊

**Comment by johlju** [comment]
Sorry it took so long. This is a case of the unit tests being written to complex (trying to reuse code too much) so it is hard to add a simple unit tests as in this case. The entire unit test should really be refactored, but no need for this PR. 🙂  

The variable `$mockDynamicIsInitialized` is used to set the value for `IsInitialized` property in the mock. Suggest adding a new context block that test this new code path. Meaning that the mock of function `Get-ReportingServicesData` should return `IsInitialized` as true and false in two different test. Though, the added `Restart-ReportingServicesService` should probably not be called if `IsInitialized -eq $true`, so that might make the new test path a bit simpler?

**Comment by johlju** [comment]
I'm closin this PR since I added this change to PR #1719 including unit tests an integration test changes. PR #1719 is also dependent on PR #1718. 
This change did make the RS 2019 correctly initialize. Great job! Sorry it took so long to get to this.

**Comment by johlju** [comment]
Btw, the WaitForSqlRs resource would try to hit the RS until it gets http status code 200. I had to add a timer of 30 seconds in the integration test after running SqlRs and before running an Invoke-WebRequest to be able for it to return http status code 200 (otherwise it returned 503). So maybe a WaitForSqlRs could help with that. 🤔 I add a issue for that so we can discuss it.

**Pull request closed without merging**
