### PR TITLE
SqlTraceflag: Correctly loads the SMO assemblies

### LINKED ISSUE #1680: SqlTraceFlag: Assembly not loaded
#### Details of the scenario you tried and the problem that is occurring
Just noticed that SqlTraceFlag has finally been added as a resource so am just trying the most basic configuration I can think of to test it out.

Unfortunately it would seem that some SQL SMO modules are not loaded and therefore the calls for `$sqlManagement = New-Object -TypeName 'Microsoft.SqlServer.Management.Smo.Wmi.ManagedComputer' -ArgumentList $ServerName` in `DSC_SqlTraceFlag.psm1` fail.

Configuration is being run on local node as an Administrator.

#### Verbose logs showing the problem
```
Cannot find type [Microsoft.SqlServer.Management.Smo.Wmi.ManagedComputer]: verify that the assembly containing this
type is loaded.
    + CategoryInfo          : InvalidType: (:) [], CimException
    + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand
    + PSComputerName        : localhost
```
#### Suggested solution to the issue

Referring to  Zuldans work, it appears there is an additional helper function `Initialize-SQLSMOAssembly` that is used to load said module(s): https://github.com/Zuldan/cSQLServerTraceFlag/blob/master/cSQLServerTraceFlagHelper.psm1#L131

Not sure if it will be helpful or not. 🤞 

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
Configuration Example
{

    Import-DscResource -ModuleName 'SqlServerDsc'

    node localhost
    {
        SqlTraceFlag 'Set_SqlTraceFlags'
        {
            InstanceName         = 'MSSQLSERVER'
            TraceFlags           = 3226
            RestartService      = $true
        }
    }
}

Example
```

#### SQL Server edition and version the target node is running
```
Microsoft SQL Server 2016 (SP2-CU15-GDR) (KB4583461) - 13.0.5865.1 (X64)
```

#### SQL Server PowerShell modules present on the target node
```
Name  Version Path
----  ------- ----
SQLPS 1.0     C:\Program Files (x86)\Microsoft SQL Server\130\Tools\PowerShell\Modules\SQLPS\SQLPS.psd1
```
#### The operating system the target node is running
```
OsName               : Microsoft Windows Server 2019 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
```

#### Version and build of PowerShell the target node is running
```
Name                           Value
----                           -----
PSVersion                      5.1.17763.1490
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.1490
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

#### Version of the DSC module that was used
```
Name         Version Path
----         ------- ----
SqlServerDsc 15.0.1  C:\Program Files\WindowsPowerShell\Modules\SqlServerDsc\15.0.1\SqlServerDsc.psd1
```

### PR DESCRIPTION
**Pull request by Fiander**
#### Pull Request (PR) description
SMO was not imported correctly. Fixed by importing sql smo.

#### This Pull Request (PR) fixes the following issues

- Fixes #1680
#### Task list

- [X] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation updated in the resource's README.md.
- [ ] Resource parameter descriptions updated in schema.mof.
- [ ] Comment-based help updated, including parameter descriptions.
- [ ] Localization strings updated.
- [ ] Examples updated.
- [ ] Unit tests updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [X] Code changes adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1682)

### CODE REVIEW

**Comment by Fiander** [comment]
I have updated the two functions by adding 
`Import-SQLPSModule 4>$null`

This imports the module, but supresses the verbose message about loading the module.
I think it would make sense to also do that in the Connect-SQL function.
That would also make the test logs a lot smaller.

**Comment by johlju** [comment]
@Fiander those `-Verbose` are due to a bug in LCM running resources (which most likely will never be fixed), but there is a way around that. We are tracking it in issue https://github.com/dsccommunity/SqlServerDsc/issues/1564. Let's fix the verbose problem when we fix it in that issue.

**Review by johlju — CHANGES_REQUESTED** [review]
Thank you for fixing this issue. Just tiny comments then this is ready to merge.

> Reviewed 2 of 10 files at r4.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1682#-:-MSDuJcoCtq9lhvKDMZr:bu530fy)* status: all files reviewed, 6 unresolved discussions (waiting on @Fiander)

*[a discussion](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1682#-MSDuS6SAzIM-yd-DFpL:-MSDuS6SAzIM-yd-DFpM:b-r593d9) (no related file):*
Please add a mock for `Import-SQLPSModule` in the unit test for the respective function.

---
___
*[CHANGELOG.md, line 9 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1682#-MSDtkIs4DKBcO7Ldhj4:-MSDtkIs4DKBcO7Ldhj5:bkwf3ac) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c3ec2e28f8de3a261b4026e0ebf2005d2d1a122a/CHANGELOG.md#L9)):*
> ```
> .·
> ```

Remove full stop (`.`) here, there is already (correctly) a full stop after the issue link.
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 36 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1682#-MSDuBDJ7Y-R77izJwk5:-MSDuBDJ7Y-R77izJwk6:b-6z4cb7) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c3ec2e28f8de3a261b4026e0ebf2005d2d1a122a/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L36)):*
> ```
> #Import SqlServer module but suppress verbose message.
> ```

We should have a space after the `#`, `# Import...`.
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 37 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1682#-MSDu05OAPtM1NHFWcbR:-MSDu05P0gTJDyJuEGZT:b30q4b6) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c3ec2e28f8de3a261b4026e0ebf2005d2d1a122a/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L37)):*
> ```
>  4>$null
> ```

Let us remove this so this won't be a problem when we fix issue https://github.com/dsccommunity/SqlServerDsc/issues/1564. 
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 151 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1682#-MSDuIDkDcaiwXYD4Tas:-MSDuIDlBQmW7Dfh5UZb:b-6z4cb7) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c3ec2e28f8de3a261b4026e0ebf2005d2d1a122a/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L151)):*
> ```
> #Import SqlServer module but suppress verbose message.
> ```

We should have a space after the `#`, `# Import...`.
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 152 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1682#-MSDu79l5O4_MQKqgrLR:-MSDu79l5O4_MQKqgrLS:b-dja8gk) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c3ec2e28f8de3a261b4026e0ebf2005d2d1a122a/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L152)):*
> ```
> 4>$null
> ```

Let us remove this so this won't be a problem when we fix issue https://github.com/dsccommunity/SqlServerDsc/issues/1564.

**Comment by johlju** [comment]
Kicked off the tests again.

**Review by johlju — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1682)* status: 0 of 3 files reviewed, 8 unresolved discussions (waiting on @Fiander and @johlju)

___
*[tests/Unit/DSC_SqlTraceFlag.Tests.ps1, line 170 at r5](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1682#-MSHXqy7EPezc8zQxrXK:-MSHXqy7EPezc8zQxrXL:brmrik4) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/df5f0f47a713551e1efa34aab0c10d1019fc4bd4/tests/Unit/DSC_SqlTraceFlag.Tests.ps1#L170)):*
> ```
> -MockWith {return}
> ```

We can skip this part if we should not return anything. It is enough with `Mock -CommandName Import-SQLPSModule`
___
*[tests/Unit/DSC_SqlTraceFlag.Tests.ps1, line 357 at r5](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1682#-MSHY3HP21zb6Dnpcoth:-MSHY3HQ-PwZ33qy6O7E:b-rdtxde) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/df5f0f47a713551e1efa34aab0c10d1019fc4bd4/tests/Unit/DSC_SqlTraceFlag.Tests.ps1#L357)):*
> ```
>  -MockWith {return}
> ```

We can skip this part if we should not return anything. It is enough with `Mock -CommandName Import-SQLPSModule`

**Review by Fiander — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1682)* status: 0 of 3 files reviewed, 8 unresolved discussions (waiting on @Fiander and @johlju)

___
*[CHANGELOG.md, line 9 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1682#-MSDtkIs4DKBcO7Ldhj4:-MSHp0vo1DzhH9H6T2TX:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c3ec2e28f8de3a261b4026e0ebf2005d2d1a122a/CHANGELOG.md#L9)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> .·
> ```

Remove full stop (`.`) here, there is already (correctly) a full stop after the issue link.
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 36 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1682#-MSDuBDJ7Y-R77izJwk5:-MSHp3lKAc9ZsczRVQyr:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c3ec2e28f8de3a261b4026e0ebf2005d2d1a122a/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L36)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> #Import SqlServer module but suppress verbose message.
> ```

We should have a space after the `#`, `# Import...`.
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 37 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1682#-MSDu05OAPtM1NHFWcbR:-MSHp5-gBrUmgF2huHYT:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c3ec2e28f8de3a261b4026e0ebf2005d2d1a122a/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L37)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>  4>$null
> ```

Let us remove this so this won't be a problem when we fix issue https://github.com/dsccommunity/SqlServerDsc/issues/1564. 
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 151 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1682#-MSDuIDkDcaiwXYD4Tas:-MSHp5XL3_oNFT1oAcz4:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c3ec2e28f8de3a261b4026e0ebf2005d2d1a122a/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L151)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> #Import SqlServer module but suppress verbose message.
> ```

We should have a space after the `#`, `# Import...`.
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 152 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1682#-MSDu79l5O4_MQKqgrLR:-MSHp5qX4atIKwoxreYP:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c3ec2e28f8de3a261b4026e0ebf2005d2d1a122a/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L152)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> 4>$null
> ```

Let us remove this so this won't be a problem when we fix issue https://github.com/dsccommunity/SqlServerDsc/issues/1564. 
</blockquote></details>

Done.
___
*[tests/Unit/DSC_SqlTraceFlag.Tests.ps1, line 170 at r5](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1682#-MSHXqy7EPezc8zQxrXK:-MSHp7KZ7M6wEwD0U0Zz:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/df5f0f47a713551e1efa34aab0c10d1019fc4bd4/tests/Unit/DSC_SqlTraceFlag.Tests.ps1#L170)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> -MockWith {return}
> ```

We can skip this part if we should not return anything. It is enough with `Mock -CommandName Import-SQLPSModule`
</blockquote></details>

Done.
___
*[tests/Unit/DSC_SqlTraceFlag.Tests.ps1, line 357 at r5](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1682#-MSHY3HP21zb6Dnpcoth:-MSHp7sv6cUN8byDqIpf:bs7wumx) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/df5f0f47a713551e1efa34aab0c10d1019fc4bd4/tests/Unit/DSC_SqlTraceFlag.Tests.ps1#L357)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>  -MockWith {return}
> ```

We can skip this part if we should not return anything. It is enough with `Mock -CommandName Import-SQLPSModule`
</blockquote></details>

Done.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1682#-:-MSIVwCb9oq2t9eacCjL:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Fiander)

**Comment by johlju** [comment]
@Fiander thank you for this fix! Much appreciated you took the time! 😃 

I will shortly push a PSSA rule soon that will help detect this issue in the future.

**Pull request merged**
