### PR TITLE
BREAKING CHANGE: SQLAlwaysOnService: Get-TargetResource should return Ensure=Absent

### LINKED ISSUE #1759: BREAKING CHANGE: SQLAlwaysOnService: Get-TargetResource should return Ensure=Absent
### Problem description

When SQL Always On is disabled and you wish to enable it,  Get-TargetResource returns
```
  Ensure = 'Present'
  IsHadrEnabled  = $false
```
 It seems odd to not just return ` Ensure = 'Absent' ` instead of having an additional parameter?

### Verbose logs

```text
ConfigurationName    :
DependsOn            :
ModuleName           : C:/ProgramData/PuppetLabs/puppet/cache/lib/puppet_x/sqlserverdsc/dsc_resources/SqlServerDsc/SqlServerDsc.psd1
ModuleVersion        : 15.2.0
PsDscRunAsCredential :
ResourceId           :
SourceInfo           :
Ensure               : Present
InstanceName         : MSSQLSERVER
IsHadrEnabled        : False
RestartTimeout       : 120
ServerName           : CORESQL02
PSComputerName       : localhost
```

### DSC configuration

```powershell
$InvokeParams = @{
  Name = 'SqlAlwaysOnService'; 
  Method = 'get'; 
  Property = @{
            Ensure               = 'Present'
            InstanceName         = 'MSSQLSERVER'
            RestartTimeout       = 120
        }; 
  ModuleName = @{
            ModuleName = 'C:/ProgramData/PuppetLabs/puppet/cache/lib/puppet_x/sqlserverdsc/dsc_resources/SqlServerDsc/SqlServerDsc.psd1'; 
            RequiredVersion = '15.2.0'}}

Invoke-DscResource @InvokeParams
```

### Suggested solution

Remove `IsHadrEnabled `and return the state in `Ensure`. Update `Test-TargetResource `to look at `Ensure` instead of `IsHadrEnabled` 

### SQL Server edition and version

```text
Microsoft SQL Server 2019 (RTM-CU16-GDR) (KB5014353) - 15.0.4236.7 (X64)   May 29 2022 15:55:47   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: )
```

### SQL Server PowerShell modules

```text
Name  Version Path
----  ------- ----
SQLPS 15.0    E:\Program Files (x86)\Microsoft SQL Server\150\Tools\PowerShell\Modules\SQLPS\SQLPS.psd1
```

### Operating system

```text
OsName               : Microsoft Windows Server 2019 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
```

### PowerShell version

```text
Name                           Value
----                           -----
PSVersion                      5.1.17763.1490
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.1490
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### SqlServerDsc version

```text
15.2.0
```

### PR DESCRIPTION
**Pull request by jrdbarnes**
#### Pull Request (PR) description
Remove IsHadrEnabled and return the state in Ensure.
Update Test-TargetResource to look at Ensure instead of IsHadrEnabled.
Update Tests to match.

#### This Pull Request (PR) fixes the following issues
- Fixes #1759

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [x] Resource documentation updated in the resource's README.md.
- [x] Resource parameter descriptions updated in schema.mof.
- [ ] Comment-based help updated, including parameter descriptions.
- [ ] Localization strings updated.
- [ ] Examples updated.
- [x] Unit tests updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Integration tests updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Code changes adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1760)

### CODE REVIEW

**Comment by jrdbarnes** [comment]
I'm not entirely sure on the Tests so may need some help. The integration tests were labelled skip, but seem to have run anyway?

**Comment by johlju** [comment]
There is a issue with a Windows patch that has broken credential decryption in LCM, so integration tests will fail until Microsoft releases a fix.

**Comment by johlju** [comment]
I will review tomorrow or this weekend. 🙂

**Comment by johlju** [comment]
I'm waiting for the build workers to get the Windows patch for DSC so the integration tests can run. I will review then.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1760#-:-N82sqJC1zlrTxYZdA4P:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jrdbarnes)

**Review by johlju — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1760)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jrdbarnes)

**Pull request merged**
