### PR TITLE
Test-IsNumericType: Function moved to DscResource.Common Module 

### LINKED ISSUE #1795: Test-IsNumericType: Move to DscResource.Common as a public command
We should look at moving this to DscResource.Common (as a public command).

### PR DESCRIPTION
**Pull request by hollanjs**
#### Pull Request (PR) description
Moved `Test-IsNumericType` from a private function in SqlServerDsc to a public function in DscResource.Common
Related Issue adding function to DscResource.Common: [Issue #87](https://github.com/dsccommunity/DscResource.Common/issues/87)

#### This Pull Request (PR) fixes the following issues
- Fixes #1795

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation updated in the resource's README.md.
- [ ] Resource parameter descriptions updated in schema.mof.
- [ ] Comment-based help updated, including parameter descriptions.
- [ ] Localization strings updated.
- [ ] Examples updated.
- [x] Unit tests updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Code changes adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1823)

### CODE REVIEW

**Comment by hollanjs** [comment]
@johlju - I think the checks are only failing because Test-IsNumericType has not been merged into DscResource.Common:main yet. That merge is queued up and ready for review as well: [DscResource.Common PR #88](https://github.com/dsccommunity/DscResource.Common/pull/88)

If it does need any additional updates, please let me know!

**Comment by johlju** [comment]
I will release DscResource.Common momentarily, then I re-run the pipeline on this PR.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1823#-:-NJV96YcAutM5i-EMRJn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hollanjs)

**Comment by johlju** [comment]
Good catch removing the private functions from the previous PR's change log entries in the Unreleased section - I would have totally forgot that 🙂

**Comment by johlju** [comment]
There seems to be a bug in other parts of the module that fails the tests, that should be unrelated to this change. I can dig into it tomorrow.

**Comment by hollanjs** [comment]
@johlju let me know if there's anything else I can do on my end.

**Comment by johlju** [comment]
I don't know how the test passed before. But good thing this bug was caught now. 🙂 

The problem was on this line:

https://github.com/dsccommunity/SqlServerDsc/blob/92612af8de4fedca3cb1438e8456428e21a44375/source/Private/Invoke-SetupAction.ps1#L1289

This line calls `Test-IsNumeric` to determine if the value is numeric. If the value is an array then `Test-IsNumericType` would wrongly return `$false` for each value, so intead of returning a single `$false` for arrays it would return an array of `$false` or `$true` for ech item, making the aboce line always evaluate to $true.

I propsed a fix in https://github.com/dsccommunity/DscResource.Common/pull/90.

**Comment by johlju** [comment]
@hollanjs thank you for this! 🙇

**Pull request merged**
