### PR TITLE
New Resource Traceflags

### PR DESCRIPTION
**Pull request by Fiander**
#### Task list

- [ ] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation updated in the resource's README.md.
- [ ] Resource parameter descriptions updated in schema.mof.
- [ ] Comment-based help updated, including parameter descriptions.
- [ ] Localization strings updated.
- [ ] Examples updated.
- [ ] Unit tests updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Code changes adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1633)

### CODE REVIEW

**Comment by johlju** [comment]
Please see issue https://github.com/dsccommunity/SqlServerDsc/issues/562. Can we avoid making a resource dedicated to traceflags and instead move into a direction that enables us to have more settings in the same resource?

**Comment by Fiander** [comment]
I have read all of those comments in  #110  and #562 before redesigning this resource. 
And yes, that would be a possibility, but i've gone trough all of the startupparameters, and except for the trace flags none is for normal usage. I would rather make a SqlServerDebug resource where i can set all of those other startup parameters.

That is also easier to manage and makes VERY clear to users that those parameters are not for normal usage.
but that is just my two cents.

the code is roughly based on zuldans code [https://github.com/Zuldan/cSQLServerTraceFlag](url)
but then with the internal SMO of SQLServerDsc

**Comment by johlju** [comment]
Some trace flags are not used for normal usage either, but I can see your point that it is more likely to use a trace flag than the other. I'm good with the route to create a SqlServerDebug resource for the other parameters. 😃  We should update that issue to point that out.

_I was just trying to avoid repeating wrong design choices that have happened before, then a resource was created for "one thing", then another for a "second thing" and later we need to merge everything it a new resource making a breaking change._ 🙂

**Comment by johlju** [comment]
We can name the resource SqlTraceFlags since Database Engine is assumed if there are no component abbreviation, see https://github.com/dsccommunity/SqlServerDsc/blob/master/CONTRIBUTING.md#naming-convention

**Comment by Fiander** [comment]
> 
> _I was just trying to avoid repeating wrong design choices that have happened before, then a resource was created for "one thing", then another for a "second thing" and later we need to merge everything it a new resource making a breaking change._ 🙂

I guess you mean: SqlMemory, SqlMaxDop and SqlConfiguration?
I agree, SqlMemory is potentially very dynamic ( especialy in a VM environment ), and MaxDop and Configuration are quite static.

but personaly, i like the idea that all of sys.configuration should be in one resource. AND that for special things special resources should be posible. Memory is in sys.configuration, But can also be configured trough SqlMemory with some kind of autotune. MaxDop can be trough Configuration, but with autotune also trough SqlMaxDop

p.s. i really dont like the autotune of SqlMemory. It is just plain wrong. 
It should include a test for full text, and substract memory for full text . 
[https://docs.microsoft.com/en-us/sql/relational-databases/search/improve-the-performance-of-full-text-indexes?view=sql-server-ver15](url)
it should also not change memory settings if the change is less then 1%.
Each time MaxMemory gets changed, the procedure cache is invalidated [https://jasonbrimhall.info/2015/01/05/effects-of-max-mem-on-plan-cache/](url)

**Comment by johlju** [comment]
Just to be clear I'm okay with your suggestion to keep this resource "standalone" (as is) but rename it to the shorter `SqlTraceFlags`. 😃 

I create a new issue for your suggestions to SqlMemory so it does not get lost. 🙂

**Comment by johlju** [comment]
> I guess you mean: SqlMemory, SqlMaxDop and SqlConfiguration

I was referencing to older resource that are no longer with us. 🙂

For the SqlMemory and SqlMaxDop there are issues (#1538, #1539) that suggest rolling them into one resource SqlProperties that could handle more properties. But I haven't really thought that one over much, so we could just close those issues.  🙂

**Comment by johlju** [comment]
I will wait for you to take this one out of draft before reviewing. 🙂

**Comment by johlju** [comment]
Closing this as you sent in a new PR for what we discussed above. 🙂

**Pull request closed without merging**
