### PR TITLE
SqlServerRole: Add support for nested roles and remove case-sensitive checks

### LINKED ISSUE #1086: SqlServerRole: Update unit tests to use the same (newest) unit test template
#### Details of the scenario you tried and the problem that is occurring
The unit tests for this resource is using an old unit test template.
Suggest we update the unit tests to use the latest unit test template.

https://github.com/PowerShell/DscResources/blob/master/Tests.Template/unit_template.ps1

#### The DSC configuration that is using the resource (as detailed as possible)
n/a

#### Version of the operating system and PowerShell the target node is running
n/a

#### SQL Server edition and version the target node is running
n/a

#### What SQL Server PowerShell modules, and which version, are present on the target node.
n/a

#### Version of the DSC module you're using, or write 'dev' if you're using current dev branch
Dev

### LINKED ISSUE #1153: SQLServerRole uses contains() which is case sensitive
get-module -name sqlserverdsc -ListAvailable

    Directory: C:\Program Files\WindowsPowerShell\Modules

ModuleType Version    Name
Manifest   11.2.0.0   SqlServerDsc

https://github.com/PowerShell/SqlServerDsc/blob/dev/DSCResources/MSFT_SqlServerRole/MSFT_SqlServerRole.psm1#L113
````
Get-DscResource sqlserverrole -syntax

SqlServerRole [String] #ResourceName
{
    InstanceName = [string]
    ServerName = [string]
    ServerRoleName = [string]
    [DependsOn = [string[]]]
    [Ensure = [string]{ Absent | Present }]
    [Members = [string[]]]
    [MembersToExclude = [string[]]]
    **[MembersToInclude = [string[]]]**
    [PsDscRunAsCredential = [PSCredential]]
}
````

The MemberstoInclude property currently uses the contains method.

if ( -not ($membersInRole.Contains($memberToInclude)))

This is case sensitive . .  .

e.g
````
$lista = 'abc','123'
$lista.Contains('abc')
> True
$lista.Contains('Abc')
> False
````

This is not desirable since possible the domain name or usename may be in a different case that the account already present on SQL.

The workaround might be to use the -In or the -contains operator.

````
$lista -contains 'abc'
>True
$lista -contains 'Abc'
> True
````

### LINKED ISSUE #1452: SqlServerRole: Add support for nested roles
#### Details of the scenario you tried and the problem that is occurring
SQL Server supports both [logins and user-defined server roles](https://docs.microsoft.com/sql/t-sql/statements/alter-server-role-transact-sql#arguments) being members of a server role. The SqlServerRole resource should be enhanced to add this support. Currently, the resource checks whether all Members, MembersToInclude, or MembersToExclude are valid Logins on the system. 

#### Verbose logs showing the problem
N/A

#### Suggested solution to the issue
Instead of solely checking for a valid Login, the resource should also validate whether it matches a Role defined in the instance.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
SqlServerRole 'Role-DBAdmins'
{
    Ensure = 'Present'
    ServerRoleName = 'DBAdmins'
    ServerName = 'sql.contoso.com'
    PsDscRunAsCredential = $SqlAdministratorCredential
}

SqlServerRole 'Role-sysadmin'
{
    Ensure = 'Present'
    ServerRoleName = 'sysadmin'
    ServerName = 'sql.constoso.com'
    MembersToInclude = 'DBAdmins'
    PsDscRunAsCredential = $SqlAdministratorCredential
}
```

#### SQL Server edition and version the target node is running
SQL 2012+

#### SQL Server PowerShell modules present on the target node
SQLPS
SqlServer
SqlServerDsc

#### The operating system the target node is running
N/A

#### Version and build of PowerShell the target node is running
N/A

#### Version of the DSC module that was used ('dev' if using current dev branch)
dev

### PR DESCRIPTION
**Pull request by nabrond**
#### Pull Request (PR) description
Adds support to the resource for nesting server role membership. Fixes an issue where role membership tests were performed in a case-sensitive manner. Updated the unit test template to v1.2.4 and refactored mocks and test structure to decrease the runtime and resolve some false test results. 

#### This Pull Request (PR) fixes the following issues
 - Fixes #1452 
 - Fixes #1153
 - Fixes #1086 
 - Partial fix of #979 

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1453)

### CODE REVIEW

**Comment by johlju** [comment]
Working on getting the new CI pipeline working, so the tests won't pass yet. I will review this and test manually. But would like to merge this once I got the new CI pipeline in.

**Comment by johlju** [comment]
The new CI pipeline has merged. This changed the folder structure, and also removed the dev branch. Please rebase against the master branch, and make sure to get your changes into the the file in the new location (under `source` folder). 😃 

Read more here about the new coding workflow: 
https://dsccommunity.org/guidelines/contributing/#understand-the-coding-workflow
https://dsccommunity.org/guidelines/testing-guidelines/#running-tests
You can also use Invoke-Pester once you run `build.ps1 -Task build` (not documented yet)
https://dsccommunity.org/guidelines/contributing/#attach-your-fork-to-a-free-azure-devops-organization

**Comment by johlju** [comment]
@nabrond What issues did you run into? Something I should document in the contribution guidelines?

**Comment by johlju** [comment]
@nabrond could you please rebase against branch master so we get rid of already merged commits (those that already been merged in other PR's)

**Comment by johlju** [comment]
I thought `git rebase` would fix that for you. 🤔 I haven't seen the problem yet. But will look out for it.

**Comment by johlju** [comment]
There are still issues with the rebase. The PR wants to remove things from the change log.
I would do this to resolve this, will this fail with the error you mentioned?

```
git checkout master
git fetch origin master
git rebase origin/master
git push my --force
git checkout nabrond-fix-sqlserverrole
git rebase my/master
# fix any conflicts
git push my --force
```

**Comment by johlju** [comment]
You could also just delete the local master branch `git branch -D master` then checkout the master from upstream again, and force push that to your fork. Then rebase your working branch against your forks master branch.

**Comment by nabrond** [comment]
@johlju, I took at look at my git history for this branch and reverted the change that I think introduced the problems with `CHANGELOG.MD`. It looks like that change came in through one off my rebase operations. Hopefully this makes this PR good to go.

**Comment by johlju** [comment]
@nabrond Awesome work on this! 😃  Thank you! Would just love to have an integration tests, and I found a little typo.

**Comment by johlju** [comment]
@nabrond I will continue the review tomorrow but a quick question in regards to the case-sensitivity. If are SQL instance is using a case-sensitive collation would that make it possible to have logins and users with different casing? 🤔 When looking at this now I thought that this might break existing use-cases by removing `.Contains()`. What are your thoughts? 🤔

**Comment by johlju** [comment]
@nabrond Thank you for the work on this! 😄

**Pull request merged**
