### PR TITLE
SqlScript, SqlScriptQuery: Add support for disable variables parameter

### LINKED ISSUE #1422: SqlScript: DisableVariables from Invoke-SQLCmd not available
Hi

I've been trying to use the SqlScript to run a T-SQL that basically create an SQL Agent Job to schedule Ola's Maintenance stored procedures.

Ola's default logging behavior use this output for each step : 
```
@output_file_name=N'D:\Microsoft SQL Server\Maintenance\$(ESCAPE_SQUOTE(JOBNAME))_$(ESCAPE_SQUOTE(STEPID))_$(ESCAPE_SQUOTE(DATE))_$(ESCAPE_SQUOTE(TIME)).txt'
```

As the script is executed by a DSC SqlScript block, the following error is thrown : 
```
PowerShell DSC resource MSFT_SqlScript  failed to execute Set-TargetResource functionality with error message: 'JOBNAME' scripting variable not defined
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
```

The internal SQL variable JOBNAME is detected as a PowerShell variable and DSC is asking to supply that variable. 

I know that an option is available with Invoke-SQLCmd to prevent that, DisableVariables.
Is there anything similar that would have not been documented I could use to keep my output_file_name ?

Thanks for your help,
Julfur

### PR DESCRIPTION
**Pull request by Kreby**
#### Pull Request (PR) description

- SqlScript
  - Added the DisabledVariables parameter
- SqlScriptQuery
  - Added the DisabledVariables parameter

This PR adds support for the DisableVariables parameter from the Invoke-SqlCmd cmdlet.  It should hopefully be relatively straight forward.  The only thing I'd point out is in the integration tests used.  I was able to keep the same SQL queries as the other tests.  Just note that when the test is run with the DisableVariables parameter it will create the database and give it the name of the variable used 

```
$(DatabaseName)
```

Despite being a bit odd looking it is a valid database name and when matched, just like the other tests, it will pass.  It does also require, as mentioned in a comment, that the database is removed after the test runs to ensure the subsequent test succeeds as well.  This is because the same variable name is used in both resource configuration data variables.  I think it should suffice but please let me know if it doesn't.

#### This Pull Request (PR) fixes the following issues

- Fixes #1422

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1578)

### CODE REVIEW

**Comment by johlju** [comment]
@Kreby Thank you for this! I might not have time to review this until the weekend due other obligations, but will get onto this as soon as I can!

**Comment by johlju** [comment]
Great work on this! Just minor changes then this is good to go. 😃

**Comment by Kreby** [comment]
@johlju thanks for the kind words/support.  I'm glad to help out.  I've not used reviewable before so I was a little disoriented on my first look 😵.  I wasn't quite sure how to respond appropriately to the individual comments with the few minutes I had. 

I'll spend sometime later today or tomorrow to figure that out, make the requested changes, and update my branch.  Thanks!

**Comment by johlju** [comment]
Yes, Reviewable can take a while to get used to (it did for me) but is awesome once you are. 🙂  Basically you just write Done as a comment when you have sent in a change for a comment, or write a comment when you want to discuss something. Once you answered the comments you like you hit the big green publish button at the top, that will publish all comments back to the PR as one big PR comment.

**Comment by johlju** [comment]
@Kreby thank you for this! I merged it and will do a full release a bit later today. 🙂

**Pull request merged**
