### PR TITLE
SqlAudit: New resources

### LINKED ISSUE #1132: New resource proposal: Server and database audit
I've been trying to use this module alongside with DSCEA to check for compliance which means I have an SQL server environment already and have run into some issues
the first is that right now the SQLserverlogin resource requires a the name of the user to check for compliance with the various password policy options. I solved this using a lot of imagination and connecting to the various SQL server instances to generate several mof files, one per computer. This one won't be fixed in all likelyhood
the second is that I have yet to find how to configure the database audit policy with DSC. is this even possible?

### PR DESCRIPTION
**Pull request by johlju**
#### Pull Request (PR) description
- SqlServerDsc
  - Add new resource SqlServerAudit.
  - The following classes were added to the module:
    - `SqlResourceBase` - class that can be inherited by class-based resource and
      provides default DSC properties and method for get a `[Server]`-object.
  - The following public functions were added to the module (see comment-based
    help for more information):
    - `Invoke-SqlDscQuery`
    - `Get-SqlDscAudit`
    - `New-SqlDscAudit`
    - `Set-SqlDscAudit`
    - `Remove-SqlDscAudit`
    - `Enable-SqlDscAudit`
    - `Disable-SqlDscAudit`
- `Get-DscProperty`
  - Added parameter `ExcludeName` to exclude property names from being returned.
- SqlPermission
  - Fix comment-based help.
- `ConvertTo-Reason`
  - Fix to handle `$null` values on Windows PowerShell.
  - If the property name contain the word 'Path' the value will be parsed to
    replace backslash or slashes at the end of the string, e.g. `'/mypath/'`
    will become `'/mypath'`.
- `ResourceBase`
  - Now handles `Ensure` correctly from derived `GetCurrentState()`. But
    requires that the `GetCurrentState()` only return key property if object
    is present, and does not return key property if object is absent.
    Optionally the resource's derived `GetCurrentState()` can handle `Ensure`
    itself.

This PR continues the work that was made in the closed PR https://github.com/dsccommunity/SqlServerDsc/pull/1433. Big thanks to @Fiander for your initial work on this! 🙂 

#### This Pull Request (PR) fixes the following issues
Fixes #1132 

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1499)

### CODE REVIEW

**Comment by Fiander** [comment]
great :-) 
It was not abanded, but you got the most resent working version.
Im struggling very much with the unit tests, I can only conclude that for those i'm not experienced yet.

so... thank you very much.

**Comment by johlju** [comment]
@Fiander I have been there too, not knowing how to write tests, but it is not that difficult once you get the hang of it and you start to see the value with them. Now I write unit tests for everything in PowerShell.

**Comment by quillypowers** [comment]
I'd definitely like to use these methods if this gains more traction.

**Comment by johlju** [comment]
I thought I would had time to write the tests for these by now. Still on the todo but far down. If someone can write unit and integration tests for these resources we can merge them

**Comment by johlju** [comment]
After spending a long time converting this project to Pester 5 I'm finally able to continue with this. 
We should rename these two resource to `SqlAudit` and `SqlAuditSpecification` to follow the current naming schema, then I will push unit tests.

**Comment by johlju** [comment]
This PR is now ready for review if someone like to dig into it. SqlAudit was refactored entirely. 

I also moved out the SqlServerAuditSpecification to a separate PR. I looked at underlaying SMO classes and it looks like it should be possible to pass one or more `[AuditSpecificationDetail]`. So I think it also need to be refactored the same way as SqlAudit was, but have a complex type that holds the information for one or more `[AuditSpecificationDetail]` . Anyone knows more about this then please let me know in PR #1779.

For SqlAudit I would like to add a a couple of evaluations of the passed parameters before `Set-SqlDscAudit`, and also handle removal an re-creating of the audit if it should be switched between File and Log or vice-verse. I might just create issues for this to be handled in other PR's.

**Review by johlju — COMMENTED** [review]
> Reviewed 1 of 25 files at r1, 47 of 56 files at r2, 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1499)* status: all files reviewed, 1 unresolved discussion

___
*[`source/en-US/SqlAudit.strings.psd1` line 17 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1499#-N9KYCkU6vZFOxeYtbIN:-N9KYCkU6vZFOxeYtbIO:bpzn5ub) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/478628cf3ba2a81fa7d3841e7d0c039a8ebf0178/source/en-US/SqlAudit.strings.psd1#L17)):*
> ```PowerShell
>     EvaluateServerAudit = Evaluate the current audit '{0}' on the instance '{1}'. (SA0004)
>     MaximumFileSizeValueInvalid = The maximum file size must be set to a value of 0 or a value between 2 and 2147483647. (SA0004)
>     QueueDelayValueInvalid = The queue delay must be set to a value of 0 or a value between 1000 and 2147483647.
> ```

We should have identifiers on the localized strings.

**Review by johlju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1499)* status: 58 of 59 files reviewed, all discussions resolved (waiting on @johlju)

___
*[`source/en-US/SqlAudit.strings.psd1` line 17 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1499#-N9KYCkU6vZFOxeYtbIN:-N9Krsab-ktCsKAce_OW:bb6un1j) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/478628cf3ba2a81fa7d3841e7d0c039a8ebf0178/source/en-US/SqlAudit.strings.psd1#L17)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We should have identifiers on the localized strings.
</blockquote></details>

Done

**Review by johlju — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1499#-:-N9Krw9B1oUCMHN92H9N:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johlju)

**Pull request merged**
